/* SPDX-License-Identifier: GPL-2.0 */
/*
 * BYR_DMSC's float-to-register encode.
 *
 * Generated by tools/camera-dmsc-encode.py --c-header; do not edit.
 *
 * Each entry says where one value from struct exynos_becore_params_dmsc lands:
 * which register, which bits of it, and the range the vendor's own translator
 * clamps it to.  The scale each value is sent at is in the UAPI header beside
 * the member, because that is where userspace reads it.
 *
 * `constant` is what `lyric::TranslateDmsc` deposits in a register whatever
 * the tuning says, so a parameter set of all zeros encodes to exactly these
 * constants -- which, because the block's `enable` reaches its register
 * inverted, is the demosaic bypassed.
 */

#ifndef __EXYNOS_BECORE_DMSC_H
#define __EXYNOS_BECORE_DMSC_H

/* The value reaches the register inverted: the block's own bypass bit. */
#define BECORE_DMSC_FIELD_INVERT		BIT(0)

/**
 * struct becore_dmsc_field - One value's place in one register
 * @offset: byte offset of the value in struct exynos_becore_params_dmsc
 * @min: the smallest value the vendor's translator will encode
 * @max: the largest
 * @shift: the bit the field starts at
 * @width: how wide it is
 * @flags: %BECORE_DMSC_FIELD_INVERT, or zero
 */
struct becore_dmsc_field {
	u32 offset;
	s32 min;
	s32 max;
	u8 shift;
	u8 width;
	u8 flags;
};

/**
 * struct becore_dmsc_reg - One register of the block's tuning
 * @offset: the register, from BECORE_RGBP_PHYS_BASE
 * @constant: the bits the translator sets whatever the tuning says
 * @first: where this register's fields start in becore_dmsc_fields[]
 * @count: how many it has
 */
struct becore_dmsc_reg {
	u16 offset;
	u32 constant;
	u16 first;
	u8 count;
};

#define BECORE_DMSC_REGS		18
#define BECORE_DMSC_FIELDS		28
#define BECORE_DMSC_VALUES		28

/*
 * The block is a flat sequence of __s32 behind its header, with no padding
 * anywhere in it, which is what lets the offsets below be generated from the
 * header's own member order.  A member added to one and not the other, or a
 * type that brought alignment with it, stops compiling here.
 */
static_assert(sizeof(struct exynos_becore_params_dmsc) ==
	      sizeof(struct v4l2_isp_params_block_header) +
	      BECORE_DMSC_VALUES * sizeof(__s32));

#define BECORE_DMSC_AT(member)	\
	offsetof(struct exynos_becore_params_dmsc, member)

static const struct becore_dmsc_field becore_dmsc_fields[] = {
	/* +0x3200 bypass [0] x1 */
	{ BECORE_DMSC_AT(enable), 0, 1, 0, 1, BECORE_DMSC_FIELD_INVERT },
	/* +0x3204 low_power_en [0] x1 */
	{ BECORE_DMSC_AT(enable_low_power), 0, 1, 0, 1, 0 },
	/* +0x321c hpf_power [0] x31 */
	{ BECORE_DMSC_AT(hpf_power), 0, 31, 0, 5, 0 },
	/* +0x3228 dir_detect [0] x127 */
	{ BECORE_DMSC_AT(gradient_weight), 0, 127, 0, 7, 0 },
	/* +0x3228 dir_detect [8] x127 */
	{ BECORE_DMSC_AT(mono_weight), 0, 127, 8, 7, 0 },
	/* +0x3228 dir_detect [16] x127 */
	{ BECORE_DMSC_AT(diagonal_weight), 0, 127, 16, 7, 0 },
	/* +0x3234 merge_dir [0] x256 */
	{ BECORE_DMSC_AT(merge_dir_contrast_threshold), 0, 256, 0, 9, 0 },
	/* +0x323c alias_detect_norm [0] x127 */
	{ BECORE_DMSC_AT(desat_strength), 0, 127, 0, 7, 0 },
	/* +0x323c alias_detect_norm [16] x4095 */
	{ BECORE_DMSC_AT(alias_detect_threshold), 0, 4095, 16, 12, 0 },
	/* +0x3240 desat_limit [0] x16 */
	{ BECORE_DMSC_AT(desat_limit), 0, 16, 0, 5, 0 },
	/* +0x3244 extract_sat [0] x255 */
	{ BECORE_DMSC_AT(extract_sat_power), 0, 255, 0, 8, 0 },
	/* +0x3248 green_detect [0] x255 */
	{ BECORE_DMSC_AT(green_detect_power), 0, 255, 0, 8, 0 },
	/* +0x325c extract_dir_grid [0] x255 */
	{ BECORE_DMSC_AT(extract_grid_hv), 0, 255, 0, 8, 0 },
	/* +0x325c extract_dir_grid [8] x255 */
	{ BECORE_DMSC_AT(extract_grid_hv_protect), 0, 255, 8, 8, 0 },
	/* +0x325c extract_dir_grid [16] x255 */
	{ BECORE_DMSC_AT(extract_dir_hv), 0, 255, 16, 8, 0 },
	/* +0x3260 extract_dir_hv_thr [0] x4095 */
	{ BECORE_DMSC_AT(extract_dir_hv_threshold), 0, 4095, 0, 12, 0 },
	/* +0x3268 add_colors [0] x255 */
	{ BECORE_DMSC_AT(add_colors_saturation_power), 0, 255, 0, 8, 0 },
	/* +0x328c edge_desat_fsharp_gain [0] x1023 */
	{ BECORE_DMSC_AT(edge_desat_fsharp_gain_p), 0, 1023, 0, 10, 0 },
	/* +0x328c edge_desat_fsharp_gain [16] x1023 */
	{ BECORE_DMSC_AT(edge_desat_fsharp_gain_m), 0, 1023, 16, 10, 0 },
	/* +0x3290 edge_desat_fsharp_thres [0] x4095 */
	{ BECORE_DMSC_AT(edge_desat_fsharp_thres_p), 0, 4095, 0, 12, 0 },
	/* +0x3290 edge_desat_fsharp_thres [16] x4095 */
	{ BECORE_DMSC_AT(edge_desat_fsharp_thres_m), 0, 4095, 16, 12, 0 },
	/* +0x3294 edge_desat_ogsharp_gain [0] x1023 */
	{ BECORE_DMSC_AT(edge_desat_ogsharp_gain_p), 0, 1023, 0, 10, 0 },
	/* +0x3294 edge_desat_ogsharp_gain [16] x1023 */
	{ BECORE_DMSC_AT(edge_desat_ogsharp_gain_m), 0, 1023, 16, 10, 0 },
	/* +0x3298 edge_desat_ogsharp_thres [0] x4095 */
	{ BECORE_DMSC_AT(edge_desat_ogsharp_thres_p), 0, 4095, 0, 12, 0 },
	/* +0x3298 edge_desat_ogsharp_thres [16] x4095 */
	{ BECORE_DMSC_AT(edge_desat_ogsharp_thres_m), 0, 4095, 16, 12, 0 },
	/* +0x329c edge_desat_limit [0] x4096 */
	{ BECORE_DMSC_AT(edge_desat_limit_p), 0, 4096, 0, 13, 0 },
	/* +0x329c edge_desat_limit [16] x4096 */
	{ BECORE_DMSC_AT(edge_desat_limit_m), 0, 4096, 16, 13, 0 },
	/* +0x32a4 edge_desat_red_preserve_gain [0] x1023 */
	{ BECORE_DMSC_AT(edge_desat_red_preserve_gain), 0, 1023, 0, 10, 0 },
};

static_assert(ARRAY_SIZE(becore_dmsc_fields) == BECORE_DMSC_FIELDS);

static const struct becore_dmsc_reg becore_dmsc_regs[] = {
	{ 0x3200, 0x00000000, 0, 1 },	/* bypass */
	{ 0x3204, 0x00000000, 1, 1 },	/* low_power_en */
	{ 0x321c, 0x00000000, 2, 1 },	/* hpf_power */
	{ 0x3228, 0x06000000, 3, 3 },	/* dir_detect */
	{ 0x3234, 0x00080000, 6, 1 },	/* merge_dir */
	{ 0x323c, 0x00000000, 7, 2 },	/* alias_detect_norm */
	{ 0x3240, 0x00000000, 9, 1 },	/* desat_limit */
	{ 0x3244, 0x00008000, 10, 1 },	/* extract_sat */
	{ 0x3248, 0x00000000, 11, 1 },	/* green_detect */
	{ 0x325c, 0x00000000, 12, 3 },	/* extract_dir_grid */
	{ 0x3260, 0x00000000, 15, 1 },	/* extract_dir_hv_thr */
	{ 0x3268, 0x00000200, 16, 1 },	/* add_colors */
	{ 0x328c, 0x00000000, 17, 2 },	/* edge_desat_fsharp_gain */
	{ 0x3290, 0x00000000, 19, 2 },	/* edge_desat_fsharp_thres */
	{ 0x3294, 0x00000000, 21, 2 },	/* edge_desat_ogsharp_gain */
	{ 0x3298, 0x00000000, 23, 2 },	/* edge_desat_ogsharp_thres */
	{ 0x329c, 0x00000000, 25, 2 },	/* edge_desat_limit */
	{ 0x32a4, 0x00000000, 27, 1 },	/* edge_desat_red_preserve_gain */
};

static_assert(ARRAY_SIZE(becore_dmsc_regs) == BECORE_DMSC_REGS);

/*
 * What GetDefaultDmsc deposits over the translator's result, so these do not
 * vary with the scene, as offsets from BECORE_RGBP_DMSC_BASE.  Every one is a
 * read-modify-write, and for all but BASE_CONFIG the preserved bits are
 * reserved; BASE_CONFIG keeps bit 0 and bit 16, the latter a real field
 * (SKIP_BYR2RGB_EN), so its literal also asserts that the tuning path left
 * both clear.
 *
 * A macro rather than an array, because this header is included before the
 * driver has declared a type to put them in.
 */
#define BECORE_DMSC_DEFAULT_COUNT	23

#define BECORE_DMSC_DEFAULTS \
	{ 0x20c, 0x0000036a },	/* base_config */ \
	{ 0x210, 0x00000000 },	/* pre_demosaicing_1 */ \
	{ 0x214, 0x00200320 },	/* pre_demosaicing_2 */ \
	{ 0x218, 0x00000280 },	/* pre_demosaicing_3 */ \
	{ 0x220, 0x00115400 },	/* ignore_rb */ \
	{ 0x224, 0x00280008 },	/* ignore_rb_1 */ \
	{ 0x22c, 0x00000008 },	/* dir_detect_hv_linear */ \
	{ 0x230, 0x00000100 },	/* contrast_minimum */ \
	{ 0x238, 0x0000007f },	/* extract_colors_config */ \
	{ 0x24c, 0x00d500b4 },	/* green_hue */ \
	{ 0x250, 0x0dac0046 },	/* green_sat */ \
	{ 0x254, 0x00000000 },	/* green_selectivity */ \
	{ 0x258, 0x00000fff },	/* post_process_config */ \
	{ 0x264, 0x00000508 },	/* dir_detect_selection */ \
	{ 0x26c, 0x000600a0 },	/* add_colors_green */ \
	{ 0x270, 0x00000120 },	/* false_colors */ \
	{ 0x274, 0x00000003 },	/* sharpening_config */ \
	{ 0x288, 0x00000001 },	/* near_edge_desat_en */ \
	{ 0x2a0, 0x00000001 },	/* edge_desat_red_preserve_en */ \
	{ 0x2a8, 0x00000000 },	/* edge_desat_red_preserve_thres */ \
	{ 0x2ac, 0x00000800 },	/* edge_desat_red_preserve_limit */ \
	{ 0x2b0, 0x00000000 },	/* desat_luma_gain */ \
	{ 0x2b4, 0x00000011 },	/* add_yblur */

/*
 * The same registers as ranges, for the generated table in the driver and for
 * the recipe generator that has to agree with it.
 */
#define BECORE_DMSC_RANGE(first, last)	\
	{ BECORE_RGBP_PHYS_BASE + (first),	\
	  BECORE_RGBP_PHYS_BASE + (last), BECORE_GEN_BYR_DMSC }

#define BECORE_DMSC_TUNING_RANGES \
	BECORE_DMSC_RANGE(0x3200, 0x3204), \
	BECORE_DMSC_RANGE(0x321c, 0x321c), \
	BECORE_DMSC_RANGE(0x3228, 0x3228), \
	BECORE_DMSC_RANGE(0x3234, 0x3234), \
	BECORE_DMSC_RANGE(0x323c, 0x3248), \
	BECORE_DMSC_RANGE(0x325c, 0x3260), \
	BECORE_DMSC_RANGE(0x3268, 0x3268), \
	BECORE_DMSC_RANGE(0x328c, 0x329c), \
	BECORE_DMSC_RANGE(0x32a4, 0x32a4),

#endif /* __EXYNOS_BECORE_DMSC_H */
