/* SPDX-License-Identifier: GPL-2.0 */
/*
 * YUVNR's float-to-register encode.
 *
 * Generated by tools/camera-yuvnr-encode.py --c-header; do not edit.
 *
 * Each entry says where one value from struct exynos_becore_params_yuvnr lands:
 * which register, which bits of it, and the range the vendor's own translators
 * clamp it to.  The scale each value is sent at is in the UAPI header beside
 * the member, because that is where userspace reads it.
 *
 * `constant` is what the translators deposit in a register regardless of the
 * tuning, so a parameter set of all zeros encodes to exactly these constants.
 */

#ifndef __EXYNOS_BECORE_YUVNR_H
#define __EXYNOS_BECORE_YUVNR_H

/* The value reaches the register inverted: the block's own bypass bit. */
#define BECORE_YUVNR_FIELD_INVERT		BIT(0)

/**
 * struct becore_yuvnr_field - One value's place in one register
 * @offset: byte offset of the value in struct exynos_becore_params_yuvnr
 * @min: the smallest value the vendor's translators will encode
 * @max: the largest
 * @shift: the bit the field starts at
 * @width: how wide it is
 * @flags: %BECORE_YUVNR_FIELD_INVERT, or zero
 */
struct becore_yuvnr_field {
	u32 offset;
	s32 min;
	s32 max;
	u8 shift;
	u8 width;
	u8 flags;
};

/**
 * struct becore_yuvnr_reg - One register of the block's tuning
 * @offset: the register, from BECORE_YUVP_PHYS_BASE
 * @constant: the bits the translators set whatever the tuning says
 * @first: where this register's fields start in becore_yuvnr_fields[]
 * @count: how many it has
 */
struct becore_yuvnr_reg {
	u16 offset;
	u32 constant;
	u16 first;
	u8 count;
};

#define BECORE_YUVNR_REGS		113
#define BECORE_YUVNR_FIELDS		215
#define BECORE_YUVNR_VALUES		194

/*
 * The block is a flat sequence of __s32 behind its header, with no padding
 * anywhere in it, which is what lets the offsets below be generated from the
 * header's own member order.  A member added to one and not the other, or a
 * type that brought alignment with it, stops compiling here.
 */
static_assert(sizeof(struct exynos_becore_params_yuvnr) ==
	      sizeof(struct v4l2_isp_params_block_header) +
	      BECORE_YUVNR_VALUES * sizeof(__s32));

#define BECORE_YUVNR_AT(member)	\
	offsetof(struct exynos_becore_params_yuvnr, member)

/*
 * Turning the low-frequency noise reducer off turns these off with it, which
 * is what the vendor's translators do rather than something chosen here.  The
 * list is measured -- the generator runs the translators again with
 * `lfnr_enable` clear and sees which fields stop being written -- so it cannot
 * drift from them.
 */
#define BECORE_YUVNR_LFNR_GATED		\
	{ BECORE_YUVNR_AT(luma_gain_enable), \
	  BECORE_YUVNR_AT(add_hf_y_enable), \
	  BECORE_YUVNR_AT(add_hf_uv_enable) }

/*
 * The bits the low-frequency stage's own branch deposits, which are not fields
 * because no single member carries one: `TranslateYuvNrCommon` writes these
 * three words from a two-armed branch and the arm taken is the one where
 * `enable` and `lfnr_enable` are *both* set, so each bit stands for the two of
 * them together.  @when_off says the bits stand where the stage is off.
 *
 * They are here rather than in the constants above because the constant would
 * be the enabled arm's answer, and every captured program has both enables on
 * -- so nothing in the corpus could tell the two apart.
 */
struct becore_yuvnr_guarded {
	u16 offset;
	u32 mask;
	bool when_off;
};

#define BECORE_YUVNR_GUARDED		\
	{ { 0x3704, 0x80000000, false }, \
	  { 0x3708, 0x80000000, false }, \
	  { 0x3758, 0x000000c6, true } }

static const struct becore_yuvnr_field becore_yuvnr_fields[] = {
	/* +0x3200 bypass [0] x1 */
	{ BECORE_YUVNR_AT(enable),
	  0, 1, 0, 1, BECORE_YUVNR_FIELD_INVERT },
	/* +0x3204 top [0] x1 */
	{ BECORE_YUVNR_AT(hfnr_enable),
	  0, 1, 0, 1, 0 },
	/* +0x3204 top [1] x1 */
	{ BECORE_YUVNR_AT(lfnr_enable),
	  0, 1, 1, 1, 0 },
	/* +0x320c controls [11] x1 */
	{ BECORE_YUVNR_AT(mcfp_weight_map_enable),
	  0, 1, 11, 1, 0 },
	/* +0x3210 support_sizes [0] x1 */
	{ BECORE_YUVNR_AT(y_support),
	  1, 5, 0, 3, 0 },
	/* +0x3210 support_sizes [16] x1 */
	{ BECORE_YUVNR_AT(slope_est_support),
	  1, 5, 16, 3, 0 },
	/* +0x3220 std_lut_x_y_0 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x3220 std_lut_x_y_0 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x3224 std_lut_x_y_1 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x3224 std_lut_x_y_1 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x3228 std_lut_x_y_2 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x3228 std_lut_x_y_2 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x322c std_lut_x_y_3 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x322c std_lut_x_y_3 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x3230 std_lut_y_y_0 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x3230 std_lut_y_y_0 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x3234 std_lut_y_y_1 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x3234 std_lut_y_y_1 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x3238 std_lut_y_y_2 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x3238 std_lut_y_y_2 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x323c std_lut_y_y_3 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x323c std_lut_y_y_3 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_y[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x3274 std_lut_x_uv_0 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x3274 std_lut_x_uv_0 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x3278 std_lut_x_uv_1 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x3278 std_lut_x_uv_1 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x327c std_lut_x_uv_2 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x327c std_lut_x_uv_2 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x3280 std_lut_x_uv_3 [0] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x3280 std_lut_x_uv_3 [16] x1 */
	{ BECORE_YUVNR_AT(std_lut_x[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x3284 std_lut_y_uv_0 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x3284 std_lut_y_uv_0 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x3288 std_lut_y_uv_1 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x3288 std_lut_y_uv_1 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x328c std_lut_y_uv_2 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x328c std_lut_y_uv_2 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x3290 std_lut_y_uv_3 [0] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x3290 std_lut_y_uv_3 [16] x4096 */
	{ BECORE_YUVNR_AT(std_lut_uv[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x32c8 std_factors [0] x16 */
	{ BECORE_YUVNR_AT(std_factor_y),
	  0, 63, 0, 6, 0 },
	/* +0x32c8 std_factors [8] x16 */
	{ BECORE_YUVNR_AT(std_factor_uv),
	  0, 63, 8, 6, 0 },
	/* +0x32c8 std_factors [16] x16 */
	{ BECORE_YUVNR_AT(std_factor_uv),
	  0, 63, 16, 6, 0 },
	/* +0x32d8 pattern_type [0] x1 */
	{ BECORE_YUVNR_AT(pattern_y),
	  0, 3, 0, 2, 0 },
	/* +0x32dc lpf_y_config [0] x1 */
	{ BECORE_YUVNR_AT(lpf_for_y_denoise),
	  0, 5, 0, 3, 0 },
	/* +0x32ec min_snr_y_config [0] x1 */
	{ BECORE_YUVNR_AT(min_snr_pix_number_low_y),
	  0, 31, 0, 5, 0 },
	/* +0x32ec min_snr_y_config [8] x1 */
	{ BECORE_YUVNR_AT(min_snr_pix_number_high_y),
	  0, 31, 8, 5, 0 },
	/* +0x32ec min_snr_y_config [16] x1 */
	{ BECORE_YUVNR_AT(min_snr_bin_width_y),
	  0, 255, 16, 8, 0 },
	/* +0x3300 min_snr_uv_config [0] x1 */
	{ BECORE_YUVNR_AT(min_snr_pix_number_low_uv),
	  0, 31, 0, 5, 0 },
	/* +0x3300 min_snr_uv_config [8] x1 */
	{ BECORE_YUVNR_AT(min_snr_pix_number_high_uv),
	  0, 31, 8, 5, 0 },
	/* +0x3300 min_snr_uv_config [16] x1 */
	{ BECORE_YUVNR_AT(min_snr_bin_width_uv),
	  0, 255, 16, 8, 0 },
	/* +0x3304 min_snr_sq_mean_y [0] x256 */
	{ BECORE_YUVNR_AT(min_snr_sq_mean_ratio_y),
	  0, 255, 0, 8, 0 },
	/* +0x3308 min_snr_sq_mean_uv [0] x256 */
	{ BECORE_YUVNR_AT(min_snr_sq_mean_ratio_uv),
	  0, 255, 0, 8, 0 },
	/* +0x3360 wavelet_nr [0] x1 */
	{ BECORE_YUVNR_AT(wavelet_nlm_relation_enable),
	  0, 1, 0, 1, 0 },
	/* +0x3360 wavelet_nr [4] x64 */
	{ BECORE_YUVNR_AT(wavelet_th_vh_gain),
	  0, 63, 4, 6, 0 },
	/* +0x3360 wavelet_nr [16] x64 */
	{ BECORE_YUVNR_AT(wavelet_th_di_gain),
	  0, 63, 16, 6, 0 },
	/* +0x336c slope_new [0] x1 */
	{ BECORE_YUVNR_AT(slope_new_enable),
	  0, 1, 0, 1, 0 },
	/* +0x336c slope_new [8] x256 */
	{ BECORE_YUVNR_AT(slope_new_thr_power),
	  0, 255, 8, 8, 0 },
	/* +0x336c slope_new [16] x1 */
	{ BECORE_YUVNR_AT(slope_new_weight_smooth_kernel),
	  0, 2, 16, 2, 0 },
	/* +0x3374 slope_new_diff [0] x256 */
	{ BECORE_YUVNR_AT(slope_new_diff_weight_coring_th),
	  0, 255, 0, 8, 0 },
	/* +0x3374 slope_new_diff [8] x256 */
	{ BECORE_YUVNR_AT(slope_new_diff_weight_gain),
	  0, 255, 8, 8, 0 },
	/* +0x3374 slope_new_diff [16] x256 */
	{ BECORE_YUVNR_AT(slope_new_diff_weight_clipping_th),
	  0, 255, 16, 8, 0 },
	/* +0x33ec tnr_wgt [0] x1 */
	{ BECORE_YUVNR_AT(mcfp_weight_mean),
	  0, 4, 0, 3, 0 },
	/* +0x33ec tnr_wgt [16] x1 */
	{ BECORE_YUVNR_AT(mcfp_center_weight),
	  0, 128, 16, 8, 0 },
	/* +0x33ec tnr_wgt [24] x1 */
	{ BECORE_YUVNR_AT(mcfp_weight_mean_in),
	  0, 1, 24, 1, 0 },
	/* +0x3420 yuv_hf_en [3] x1 */
	{ BECORE_YUVNR_AT(uv_support),
	  2, 6, 3, 3, 0 },
	/* +0x3424 biquad_factor_y [0] x1024 */
	{ BECORE_YUVNR_AT(radial_gain_a_y),
	  0, 8191, 0, 13, 0 },
	/* +0x3424 biquad_factor_y [16] x1024 */
	{ BECORE_YUVNR_AT(radial_gain_b_y),
	  0, 8191, 16, 13, 0 },
	/* +0x3428 biquad_factor_uv [0] x1024 */
	{ BECORE_YUVNR_AT(radial_gain_a_uv),
	  0, 8191, 0, 13, 0 },
	/* +0x3428 biquad_factor_uv [16] x1024 */
	{ BECORE_YUVNR_AT(radial_gain_b_uv),
	  0, 8191, 16, 13, 0 },
	/* +0x342c tnr_tnr_thr_min_1 [0] x256 */
	{ BECORE_YUVNR_AT(mcfp_y_hfnr_min_ratio),
	  0, 256, 0, 9, 0 },
	/* +0x342c tnr_tnr_thr_min_1 [16] x256 */
	{ BECORE_YUVNR_AT(mcfp_uv_hfnr_min_ratio),
	  0, 256, 16, 9, 0 },
	/* +0x3430 tnr_tnr_thr_min_2 [0] x256 */
	{ BECORE_YUVNR_AT(mcfp_uv_hfnr_min_ratio),
	  0, 256, 0, 9, 0 },
	/* +0x3434 tnr_lut_y_0 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[0]),
	  0, 4096, 0, 13, 0 },
	/* +0x3438 tnr_lut_y_1 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[1]),
	  0, 4096, 0, 13, 0 },
	/* +0x343c tnr_lut_y_2 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[2]),
	  0, 4096, 0, 13, 0 },
	/* +0x3440 tnr_lut_y_3 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[3]),
	  0, 4096, 0, 13, 0 },
	/* +0x3444 tnr_lut_y_4 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[4]),
	  0, 4096, 0, 13, 0 },
	/* +0x3448 tnr_lut_y_5 [0] x4096 */
	{ BECORE_YUVNR_AT(mcfp_gain_lut_y[5]),
	  0, 4096, 0, 13, 0 },
	/* +0x351c luma_gain_config [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_enable),
	  0, 1, 0, 1, 0 },
	/* +0x3574 luma_gain_y_pnts_tbl_0 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[0]),
	  0, 255, 0, 8, 0 },
	/* +0x3574 luma_gain_y_pnts_tbl_0 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[1]),
	  0, 255, 16, 8, 0 },
	/* +0x3578 luma_gain_y_pnts_tbl_1 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[2]),
	  0, 255, 0, 8, 0 },
	/* +0x3578 luma_gain_y_pnts_tbl_1 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[3]),
	  0, 255, 16, 8, 0 },
	/* +0x357c luma_gain_y_pnts_tbl_2 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[4]),
	  0, 255, 0, 8, 0 },
	/* +0x357c luma_gain_y_pnts_tbl_2 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[5]),
	  0, 255, 16, 8, 0 },
	/* +0x3580 luma_gain_y_pnts_tbl_3 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[6]),
	  0, 255, 0, 8, 0 },
	/* +0x3580 luma_gain_y_pnts_tbl_3 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[7]),
	  0, 255, 16, 8, 0 },
	/* +0x3584 luma_gain_y_pnts_tbl_4 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[8]),
	  0, 255, 0, 8, 0 },
	/* +0x3584 luma_gain_y_pnts_tbl_4 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[9]),
	  0, 255, 16, 8, 0 },
	/* +0x3588 luma_gain_y_pnts_tbl_5 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[10]),
	  0, 255, 0, 8, 0 },
	/* +0x3588 luma_gain_y_pnts_tbl_5 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[11]),
	  0, 255, 16, 8, 0 },
	/* +0x358c luma_gain_y_pnts_tbl_6 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[12]),
	  0, 255, 0, 8, 0 },
	/* +0x358c luma_gain_y_pnts_tbl_6 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[13]),
	  0, 255, 16, 8, 0 },
	/* +0x3590 luma_gain_y_pnts_tbl_7 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[14]),
	  0, 255, 0, 8, 0 },
	/* +0x3590 luma_gain_y_pnts_tbl_7 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[15]),
	  0, 255, 16, 8, 0 },
	/* +0x3594 luma_gain_y_pnts_tbl_8 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[16]),
	  0, 255, 0, 8, 0 },
	/* +0x3594 luma_gain_y_pnts_tbl_8 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[17]),
	  0, 255, 16, 8, 0 },
	/* +0x3598 luma_gain_y_pnts_tbl_9 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[18]),
	  0, 255, 0, 8, 0 },
	/* +0x3598 luma_gain_y_pnts_tbl_9 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[19]),
	  0, 255, 16, 8, 0 },
	/* +0x359c luma_gain_y_pnts_tbl_10 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[20]),
	  0, 255, 0, 8, 0 },
	/* +0x359c luma_gain_y_pnts_tbl_10 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[21]),
	  0, 255, 16, 8, 0 },
	/* +0x35a0 luma_gain_y_pnts_tbl_11 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[22]),
	  0, 255, 0, 8, 0 },
	/* +0x35a0 luma_gain_y_pnts_tbl_11 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[23]),
	  0, 255, 16, 8, 0 },
	/* +0x35a4 luma_gain_y_pnts_tbl_12 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[24]),
	  0, 255, 0, 8, 0 },
	/* +0x35a4 luma_gain_y_pnts_tbl_12 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[25]),
	  0, 255, 16, 8, 0 },
	/* +0x35a8 luma_gain_y_pnts_tbl_13 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[26]),
	  0, 255, 0, 8, 0 },
	/* +0x35a8 luma_gain_y_pnts_tbl_13 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[27]),
	  0, 255, 16, 8, 0 },
	/* +0x35ac luma_gain_y_pnts_tbl_14 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[28]),
	  0, 255, 0, 8, 0 },
	/* +0x35ac luma_gain_y_pnts_tbl_14 [16] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[29]),
	  0, 255, 16, 8, 0 },
	/* +0x35b0 luma_gain_y_pnts_tbl_15 [0] x1 */
	{ BECORE_YUVNR_AT(luma_gain_y[30]),
	  0, 255, 0, 8, 0 },
	/* +0x35d4 vertfilterlength [0] x1 */
	{ BECORE_YUVNR_AT(vert_filter_length),
	  0, 10, 0, 4, 0 },
	/* +0x35d4 vertfilterlength [4] x1 */
	{ BECORE_YUVNR_AT(vert_filter_length),
	  0, 10, 4, 4, 0 },
	/* +0x35e4 v_sigma [0] x4096 */
	{ BECORE_YUVNR_AT(v_sigma_y),
	  0, 4095, 0, 12, 0 },
	/* +0x35e4 v_sigma [16] x4096 */
	{ BECORE_YUVNR_AT(v_sigma_uv),
	  0, 4095, 16, 12, 0 },
	/* +0x35e8 v_sigma_up [0] x4096 */
	{ BECORE_YUVNR_AT(v_sigma_y),
	  0, 4095, 0, 12, 0 },
	/* +0x35e8 v_sigma_up [16] x4096 */
	{ BECORE_YUVNR_AT(v_sigma_uv),
	  0, 4095, 16, 12, 0 },
	/* +0x3600 v_guided_eps_0 [0] x4096 */
	{ BECORE_YUVNR_AT(vertical_gf_eps[0]),
	  3, 4095, 0, 12, 0 },
	/* +0x3600 v_guided_eps_0 [16] x4096 */
	{ BECORE_YUVNR_AT(vertical_gf_eps[1]),
	  3, 4095, 16, 12, 0 },
	/* +0x3604 v_guided_eps_1 [0] x4096 */
	{ BECORE_YUVNR_AT(vertical_gf_eps[2]),
	  3, 4095, 0, 12, 0 },
	/* +0x3618 h_level2 [0] x16384 */
	{ BECORE_YUVNR_AT(h_sigma_y_level2),
	  0, 16383, 0, 14, 0 },
	/* +0x3618 h_level2 [16] x16384 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level2),
	  0, 16383, 16, 14, 0 },
	/* +0x361c h_level2_up [0] x16384 */
	{ BECORE_YUVNR_AT(h_sigma_y_level2),
	  0, 16383, 0, 14, 0 },
	/* +0x361c h_level2_up [16] x16384 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level2),
	  0, 16383, 16, 14, 0 },
	/* +0x3628 h_level1 [0] x8192 */
	{ BECORE_YUVNR_AT(h_sigma_y_level1),
	  0, 8191, 0, 13, 0 },
	/* +0x3628 h_level1 [16] x8192 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level1),
	  0, 8191, 16, 13, 0 },
	/* +0x362c h_level1_up [0] x8192 */
	{ BECORE_YUVNR_AT(h_sigma_y_level1),
	  0, 8191, 0, 13, 0 },
	/* +0x362c h_level1_up [16] x8192 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level1),
	  0, 8191, 16, 13, 0 },
	/* +0x3638 h_level0 [0] x4096 */
	{ BECORE_YUVNR_AT(h_sigma_y_level0),
	  0, 4095, 0, 12, 0 },
	/* +0x3638 h_level0 [16] x4096 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level0),
	  0, 4095, 16, 12, 0 },
	/* +0x363c h_level0_up [0] x4096 */
	{ BECORE_YUVNR_AT(h_sigma_y_level0),
	  0, 4095, 0, 12, 0 },
	/* +0x363c h_level0_up [16] x4096 */
	{ BECORE_YUVNR_AT(h_sigma_uv_level0),
	  0, 4095, 16, 12, 0 },
	/* +0x3664 multiscale_hcoring_l1_0 [0] x8192 */
	{ BECORE_YUVNR_AT(h_coring_l1_0),
	  0, 8191, 0, 13, 0 },
	/* +0x3668 multiscale_hcoring_l1_1 [0] x4096 */
	{ BECORE_YUVNR_AT(h_coring_l1_1),
	  0, 4095, 0, 12, 0 },
	/* +0x3668 multiscale_hcoring_l1_1 [16] x4096 */
	{ BECORE_YUVNR_AT(h_coring_l1_2),
	  0, 4095, 16, 12, 0 },
	/* +0x3670 multiscale_hcoring_l2_0 [0] x16384 */
	{ BECORE_YUVNR_AT(h_coring_l2_0),
	  0, 16383, 0, 14, 0 },
	/* +0x3674 multiscale_hcoring_l2_1 [0] x8192 */
	{ BECORE_YUVNR_AT(h_coring_l2_1),
	  0, 8191, 0, 13, 0 },
	/* +0x3674 multiscale_hcoring_l2_1 [16] x8192 */
	{ BECORE_YUVNR_AT(h_coring_l2_2),
	  0, 8191, 16, 13, 0 },
	/* +0x367c multiscale_hcoring_gain [0] x8 */
	{ BECORE_YUVNR_AT(h_coring_gain_uv_l1),
	  0, 8, 0, 4, 0 },
	/* +0x367c multiscale_hcoring_gain [4] x8 */
	{ BECORE_YUVNR_AT(h_coring_gain_uv_l2),
	  0, 8, 4, 4, 0 },
	/* +0x36ec addhf [0] x1 */
	{ BECORE_YUVNR_AT(add_hf_y_enable),
	  0, 1, 0, 1, 0 },
	/* +0x36ec addhf [1] x1 */
	{ BECORE_YUVNR_AT(add_hf_uv_enable),
	  0, 1, 1, 1, 0 },
	/* +0x36f4 hf_y_coring_th [0] x1 */
	{ BECORE_YUVNR_AT(add_hf_y_enable),
	  0, 1, 0, 1, 0 },
	/* +0x36f4 hf_y_coring_th [16] x4096 */
	{ BECORE_YUVNR_AT(hf_y_coring_th),
	  0, 4095, 16, 12, 0 },
	/* +0x36f8 hf_u_coring_th [0] x1 */
	{ BECORE_YUVNR_AT(add_hf_uv_enable),
	  0, 1, 0, 1, 0 },
	/* +0x36f8 hf_u_coring_th [16] x2048 */
	{ BECORE_YUVNR_AT(hf_uv_coring_th),
	  0, 2047, 16, 11, 0 },
	/* +0x3700 hf_v_coring_th [0] x2048 */
	{ BECORE_YUVNR_AT(hf_uv_coring_th),
	  0, 2047, 0, 11, 0 },
	/* +0x3700 hf_v_coring_th [16] x1 */
	{ BECORE_YUVNR_AT(add_hf_uv_enable),
	  0, 1, 16, 1, 0 },
	/* +0x3704 filtersweights_param0 [0] x1 */
	{ BECORE_YUVNR_AT(lpf_y[0]),
	  0, 10, 0, 4, 0 },
	/* +0x3704 filtersweights_param0 [4] x1 */
	{ BECORE_YUVNR_AT(lpf_y[1]),
	  0, 10, 4, 4, 0 },
	/* +0x3704 filtersweights_param0 [8] x1 */
	{ BECORE_YUVNR_AT(lpf_y[2]),
	  0, 10, 8, 4, 0 },
	/* +0x3708 filterweights_param1 [0] x1 */
	{ BECORE_YUVNR_AT(lpf_uv[0]),
	  0, 5, 0, 3, 0 },
	/* +0x3708 filterweights_param1 [4] x1 */
	{ BECORE_YUVNR_AT(lpf_uv[1]),
	  0, 5, 4, 3, 0 },
	/* +0x3708 filterweights_param1 [8] x1 */
	{ BECORE_YUVNR_AT(lpf_uv[2]),
	  0, 5, 8, 3, 0 },
	/* +0x370c filterweights_param2 [0] x1 */
	{ BECORE_YUVNR_AT(fallback_long_y_filter_width[0]),
	  0, 6, 0, 3, 0 },
	/* +0x370c filterweights_param2 [4] x1 */
	{ BECORE_YUVNR_AT(fallback_long_y_filter_width[1]),
	  0, 6, 4, 3, 0 },
	/* +0x370c filterweights_param2 [8] x1 */
	{ BECORE_YUVNR_AT(fallback_long_y_filter_width[2]),
	  0, 6, 8, 3, 0 },
	/* +0x375c output_param0 [0] x1 */
	{ BECORE_YUVNR_AT(vert_long_th_radial_luma_enable),
	  0, 1, 0, 1, 0 },
	/* +0x375c output_param0 [8] x16 */
	{ BECORE_YUVNR_AT(vert_long_gain[0]),
	  0, 16, 8, 5, 0 },
	/* +0x375c output_param0 [16] x16 */
	{ BECORE_YUVNR_AT(vert_long_gain[1]),
	  0, 16, 16, 5, 0 },
	/* +0x375c output_param0 [24] x16 */
	{ BECORE_YUVNR_AT(vert_long_gain[2]),
	  0, 16, 24, 5, 0 },
	/* +0x3760 output_param1 [0] x4096 */
	{ BECORE_YUVNR_AT(vert_long_th_0),
	  0, 4095, 0, 12, 0 },
	/* +0x3764 output_param2 [0] x2048 */
	{ BECORE_YUVNR_AT(vert_long_th_1),
	  0, 2047, 0, 11, 0 },
	/* +0x3764 output_param2 [16] x2048 */
	{ BECORE_YUVNR_AT(vert_long_th_2),
	  0, 2047, 16, 11, 0 },
	/* +0x3768 output_param3 [0] x1 */
	{ BECORE_YUVNR_AT(fallback_hpf_y_th_radial_luma_enable),
	  0, 1, 0, 1, 0 },
	/* +0x3768 output_param3 [8] x16 */
	{ BECORE_YUVNR_AT(fallback_hpf_y_gain),
	  0, 16, 8, 5, 0 },
	/* +0x3768 output_param3 [16] x4096 */
	{ BECORE_YUVNR_AT(fallback_hpf_y_th),
	  0, 4095, 16, 12, 0 },
	/* +0x376c output_param4 [0] x1 */
	{ BECORE_YUVNR_AT(fallback_long_y_th_radial_luma_enable),
	  0, 1, 0, 1, 0 },
	/* +0x376c output_param4 [8] x16 */
	{ BECORE_YUVNR_AT(fallback_long_y_gain),
	  0, 16, 8, 5, 0 },
	/* +0x376c output_param4 [16] x4096 */
	{ BECORE_YUVNR_AT(fallback_long_y_th),
	  0, 4095, 16, 12, 0 },
	/* +0x3770 output_param5 [0] x4096 */
	{ BECORE_YUVNR_AT(noise_addback_y_th),
	  0, 4095, 0, 12, 0 },
	/* +0x3770 output_param5 [16] x1 */
	{ BECORE_YUVNR_AT(noise_addback_y_enable),
	  0, 1, 16, 1, 0 },
	/* +0x3770 output_param5 [17] x1 */
	{ BECORE_YUVNR_AT(noise_addback_th_radial_luma_enable),
	  0, 1, 17, 1, 0 },
	/* +0x3774 output_param6 [0] x1 */
	{ BECORE_YUVNR_AT(noise_addback_uv_enable),
	  0, 1, 0, 1, 0 },
	/* +0x3774 output_param6 [16] x2048 */
	{ BECORE_YUVNR_AT(noise_addback_uv_th),
	  0, 2047, 16, 11, 0 },
	/* +0x3778 output_param7 [0] x4096 */
	{ BECORE_YUVNR_AT(noise_addback_y_clip),
	  0, 4095, 0, 12, 0 },
	/* +0x3778 output_param7 [16] x256 */
	{ BECORE_YUVNR_AT(noise_addback_y_gain),
	  0, 256, 16, 9, 0 },
	/* +0x377c output_param8 [0] x2048 */
	{ BECORE_YUVNR_AT(noise_addback_uv_clip),
	  0, 2047, 0, 11, 0 },
	/* +0x377c output_param8 [16] x256 */
	{ BECORE_YUVNR_AT(noise_addback_uv_gain),
	  0, 256, 16, 9, 0 },
	/* +0x3780 addhf_gain [0] x256 */
	{ BECORE_YUVNR_AT(add_hf_uv_gain),
	  0, 256, 0, 9, 0 },
	/* +0x378c hgain_0to1 [0] x4096 */
	{ BECORE_YUVNR_AT(h_gain[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x378c hgain_0to1 [16] x4096 */
	{ BECORE_YUVNR_AT(h_gain[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x3790 hgain_2to3 [0] x4096 */
	{ BECORE_YUVNR_AT(h_gain[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x3790 hgain_2to3 [16] x4096 */
	{ BECORE_YUVNR_AT(h_gain[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x3794 hgain_4to5 [0] x4096 */
	{ BECORE_YUVNR_AT(h_gain[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x3794 hgain_4to5 [16] x4096 */
	{ BECORE_YUVNR_AT(h_gain[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x3798 hgain_6to7 [0] x4096 */
	{ BECORE_YUVNR_AT(h_gain[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x3798 hgain_6to7 [16] x4096 */
	{ BECORE_YUVNR_AT(h_gain[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x379c hgain_8 [0] x4096 */
	{ BECORE_YUVNR_AT(h_gain[8]),
	  0, 4095, 0, 12, 0 },
	/* +0x37a0 vgain_0to1 [0] x4096 */
	{ BECORE_YUVNR_AT(v_gain[0]),
	  0, 4095, 0, 12, 0 },
	/* +0x37a0 vgain_0to1 [16] x4096 */
	{ BECORE_YUVNR_AT(v_gain[1]),
	  0, 4095, 16, 12, 0 },
	/* +0x37a4 vgain_2to3 [0] x4096 */
	{ BECORE_YUVNR_AT(v_gain[2]),
	  0, 4095, 0, 12, 0 },
	/* +0x37a4 vgain_2to3 [16] x4096 */
	{ BECORE_YUVNR_AT(v_gain[3]),
	  0, 4095, 16, 12, 0 },
	/* +0x37a8 vgain_4to5 [0] x4096 */
	{ BECORE_YUVNR_AT(v_gain[4]),
	  0, 4095, 0, 12, 0 },
	/* +0x37a8 vgain_4to5 [16] x4096 */
	{ BECORE_YUVNR_AT(v_gain[5]),
	  0, 4095, 16, 12, 0 },
	/* +0x37ac vgain_6to7 [0] x4096 */
	{ BECORE_YUVNR_AT(v_gain[6]),
	  0, 4095, 0, 12, 0 },
	/* +0x37ac vgain_6to7 [16] x4096 */
	{ BECORE_YUVNR_AT(v_gain[7]),
	  0, 4095, 16, 12, 0 },
	/* +0x37b0 vgain_8 [0] x4096 */
	{ BECORE_YUVNR_AT(v_gain[8]),
	  0, 4095, 0, 12, 0 },
	/* +0x37b4 wide_gain [0] x4096 */
	{ BECORE_YUVNR_AT(wide_gain_y),
	  0, 4095, 0, 12, 0 },
	/* +0x37b4 wide_gain [16] x4096 */
	{ BECORE_YUVNR_AT(wide_gain_uv),
	  0, 4095, 16, 12, 0 },
	/* +0x37b8 hfnr_return_noise_en [0] x1 */
	{ BECORE_YUVNR_AT(return_noise_y_enable),
	  0, 1, 0, 1, 0 },
	/* +0x37b8 hfnr_return_noise_en [4] x1 */
	{ BECORE_YUVNR_AT(return_noise_uv_enable),
	  0, 1, 4, 1, 0 },
	/* +0x37b8 hfnr_return_noise_en [12] x1 */
	{ BECORE_YUVNR_AT(return_noise_adaptive_coring),
	  0, 1, 12, 1, 0 },
	/* +0x37b8 hfnr_return_noise_en [16] x1 */
	{ BECORE_YUVNR_AT(return_noise_adaptive_coring),
	  0, 1, 16, 1, 0 },
	/* +0x37b8 hfnr_return_noise_en [20] x1 */
	{ BECORE_YUVNR_AT(return_noise_adaptive_power),
	  0, 1, 20, 1, 0 },
	/* +0x37bc hfnr_return_noise_coring_y [0] x4096 */
	{ BECORE_YUVNR_AT(return_noise_coring_threshold_y),
	  0, 4095, 0, 12, 0 },
	/* +0x37c0 hfnr_return_noise_coring_uv [0] x4096 */
	{ BECORE_YUVNR_AT(return_noise_coring_threshold_uv),
	  0, 4095, 0, 12, 0 },
	/* +0x37c0 hfnr_return_noise_coring_uv [16] x4096 */
	{ BECORE_YUVNR_AT(return_noise_coring_threshold_uv),
	  0, 4095, 16, 12, 0 },
	/* +0x37c4 hfnr_return_noise_factor_y [0] x1024 */
	{ BECORE_YUVNR_AT(return_noise_power_y),
	  0, 1024, 0, 11, 0 },
	/* +0x37c4 hfnr_return_noise_factor_y [16] x1 */
	{ BECORE_YUVNR_AT(return_noise_power_shifter_y),
	  0, 12, 16, 4, 0 },
	/* +0x37c8 hfnr_return_noise_factor_uv [0] x1024 */
	{ BECORE_YUVNR_AT(return_noise_power_uv),
	  0, 1024, 0, 11, 0 },
	/* +0x37c8 hfnr_return_noise_factor_uv [12] x1024 */
	{ BECORE_YUVNR_AT(return_noise_power_uv),
	  0, 1024, 12, 11, 0 },
	/* +0x37c8 hfnr_return_noise_factor_uv [24] x1 */
	{ BECORE_YUVNR_AT(return_noise_power_shifter_uv),
	  0, 12, 24, 4, 0 },
	/* +0x37c8 hfnr_return_noise_factor_uv [28] x1 */
	{ BECORE_YUVNR_AT(return_noise_power_shifter_uv),
	  0, 12, 28, 4, 0 },
	/* +0x37cc hfnr_return_noise_limit_y [0] x4096 */
	{ BECORE_YUVNR_AT(return_noise_limit_y),
	  0, 4095, 0, 12, 0 },
	/* +0x37d0 hfnr_return_noise_limit_uv [0] x4096 */
	{ BECORE_YUVNR_AT(return_noise_limit_uv),
	  0, 4095, 0, 12, 0 },
	/* +0x37d0 hfnr_return_noise_limit_uv [16] x4096 */
	{ BECORE_YUVNR_AT(return_noise_limit_uv),
	  0, 4095, 16, 12, 0 },
};

static_assert(ARRAY_SIZE(becore_yuvnr_fields) == BECORE_YUVNR_FIELDS);

static const struct becore_yuvnr_reg becore_yuvnr_regs[] = {
	{ 0x3200, 0x00000000, 0, 1 },	/* bypass */
	{ 0x3204, 0x00000000, 1, 2 },	/* top */
	{ 0x320c, 0x00000218, 3, 1 },	/* controls */
	{ 0x3210, 0x00000000, 4, 2 },	/* support_sizes */
	{ 0x3220, 0x00000000, 6, 2 },	/* std_lut_x_y_0 */
	{ 0x3224, 0x00000000, 8, 2 },	/* std_lut_x_y_1 */
	{ 0x3228, 0x00000000, 10, 2 },	/* std_lut_x_y_2 */
	{ 0x322c, 0x00000000, 12, 2 },	/* std_lut_x_y_3 */
	{ 0x3230, 0x00000000, 14, 2 },	/* std_lut_y_y_0 */
	{ 0x3234, 0x00000000, 16, 2 },	/* std_lut_y_y_1 */
	{ 0x3238, 0x00000000, 18, 2 },	/* std_lut_y_y_2 */
	{ 0x323c, 0x00000000, 20, 2 },	/* std_lut_y_y_3 */
	{ 0x3274, 0x00000000, 22, 2 },	/* std_lut_x_uv_0 */
	{ 0x3278, 0x00000000, 24, 2 },	/* std_lut_x_uv_1 */
	{ 0x327c, 0x00000000, 26, 2 },	/* std_lut_x_uv_2 */
	{ 0x3280, 0x00000000, 28, 2 },	/* std_lut_x_uv_3 */
	{ 0x3284, 0x00000000, 30, 2 },	/* std_lut_y_uv_0 */
	{ 0x3288, 0x00000000, 32, 2 },	/* std_lut_y_uv_1 */
	{ 0x328c, 0x00000000, 34, 2 },	/* std_lut_y_uv_2 */
	{ 0x3290, 0x00000000, 36, 2 },	/* std_lut_y_uv_3 */
	{ 0x32c8, 0x22000000, 38, 3 },	/* std_factors */
	{ 0x32d8, 0x00000000, 41, 1 },	/* pattern_type */
	{ 0x32dc, 0x00000000, 42, 1 },	/* lpf_y_config */
	{ 0x32ec, 0x00000000, 43, 3 },	/* min_snr_y_config */
	{ 0x3300, 0x00000000, 46, 3 },	/* min_snr_uv_config */
	{ 0x3304, 0x00000100, 49, 1 },	/* min_snr_sq_mean_y */
	{ 0x3308, 0x00000100, 50, 1 },	/* min_snr_sq_mean_uv */
	{ 0x3360, 0x00000000, 51, 3 },	/* wavelet_nr */
	{ 0x336c, 0x00000000, 54, 3 },	/* slope_new */
	{ 0x3374, 0x00000000, 57, 3 },	/* slope_new_diff */
	{ 0x33ec, 0x00000400, 60, 3 },	/* tnr_wgt */
	{ 0x3420, 0x00000006, 63, 1 },	/* yuv_hf_en */
	{ 0x3424, 0x00000000, 64, 2 },	/* biquad_factor_y */
	{ 0x3428, 0x00000000, 66, 2 },	/* biquad_factor_uv */
	{ 0x342c, 0x00000000, 68, 2 },	/* tnr_tnr_thr_min_1 */
	{ 0x3430, 0x00000000, 70, 1 },	/* tnr_tnr_thr_min_2 */
	{ 0x3434, 0x00000000, 71, 1 },	/* tnr_lut_y_0 */
	{ 0x3438, 0x00000000, 72, 1 },	/* tnr_lut_y_1 */
	{ 0x343c, 0x00000000, 73, 1 },	/* tnr_lut_y_2 */
	{ 0x3440, 0x00000000, 74, 1 },	/* tnr_lut_y_3 */
	{ 0x3444, 0x00000000, 75, 1 },	/* tnr_lut_y_4 */
	{ 0x3448, 0x00000000, 76, 1 },	/* tnr_lut_y_5 */
	{ 0x351c, 0x00000000, 77, 1 },	/* luma_gain_config */
	{ 0x3574, 0x00000000, 78, 2 },	/* luma_gain_y_pnts_tbl_0 */
	{ 0x3578, 0x00000000, 80, 2 },	/* luma_gain_y_pnts_tbl_1 */
	{ 0x357c, 0x00000000, 82, 2 },	/* luma_gain_y_pnts_tbl_2 */
	{ 0x3580, 0x00000000, 84, 2 },	/* luma_gain_y_pnts_tbl_3 */
	{ 0x3584, 0x00000000, 86, 2 },	/* luma_gain_y_pnts_tbl_4 */
	{ 0x3588, 0x00000000, 88, 2 },	/* luma_gain_y_pnts_tbl_5 */
	{ 0x358c, 0x00000000, 90, 2 },	/* luma_gain_y_pnts_tbl_6 */
	{ 0x3590, 0x00000000, 92, 2 },	/* luma_gain_y_pnts_tbl_7 */
	{ 0x3594, 0x00000000, 94, 2 },	/* luma_gain_y_pnts_tbl_8 */
	{ 0x3598, 0x00000000, 96, 2 },	/* luma_gain_y_pnts_tbl_9 */
	{ 0x359c, 0x00000000, 98, 2 },	/* luma_gain_y_pnts_tbl_10 */
	{ 0x35a0, 0x00000000, 100, 2 },	/* luma_gain_y_pnts_tbl_11 */
	{ 0x35a4, 0x00000000, 102, 2 },	/* luma_gain_y_pnts_tbl_12 */
	{ 0x35a8, 0x00000000, 104, 2 },	/* luma_gain_y_pnts_tbl_13 */
	{ 0x35ac, 0x00000000, 106, 2 },	/* luma_gain_y_pnts_tbl_14 */
	{ 0x35b0, 0x00000000, 108, 1 },	/* luma_gain_y_pnts_tbl_15 */
	{ 0x35c4, 0x00000007, 109, 0 },	/* v_nr_en */
	{ 0x35cc, 0x00000001, 109, 0 },	/* iir_two_coef */
	{ 0x35d4, 0x00000000, 109, 2 },	/* vertfilterlength */
	{ 0x35e4, 0x00000000, 111, 2 },	/* v_sigma */
	{ 0x35e8, 0x00000000, 113, 2 },	/* v_sigma_up */
	{ 0x3600, 0x00000000, 115, 2 },	/* v_guided_eps_0 */
	{ 0x3604, 0x00000000, 117, 1 },	/* v_guided_eps_1 */
	{ 0x3618, 0x00000000, 118, 2 },	/* h_level2 */
	{ 0x361c, 0x00000000, 120, 2 },	/* h_level2_up */
	{ 0x3628, 0x00000000, 122, 2 },	/* h_level1 */
	{ 0x362c, 0x00000000, 124, 2 },	/* h_level1_up */
	{ 0x3638, 0x00000000, 126, 2 },	/* h_level0 */
	{ 0x363c, 0x00000000, 128, 2 },	/* h_level0_up */
	{ 0x3664, 0x00000000, 130, 1 },	/* multiscale_hcoring_l1_0 */
	{ 0x3668, 0x00000000, 131, 2 },	/* multiscale_hcoring_l1_1 */
	{ 0x3670, 0x00000000, 133, 1 },	/* multiscale_hcoring_l2_0 */
	{ 0x3674, 0x00000000, 134, 2 },	/* multiscale_hcoring_l2_1 */
	{ 0x367c, 0x00000000, 136, 2 },	/* multiscale_hcoring_gain */
	{ 0x36ec, 0x00000000, 138, 2 },	/* addhf */
	{ 0x36f4, 0x00000000, 140, 2 },	/* hf_y_coring_th */
	{ 0x36f8, 0x00000000, 142, 2 },	/* hf_u_coring_th */
	{ 0x3700, 0x00000000, 144, 2 },	/* hf_v_coring_th */
	{ 0x3704, 0x00000000, 146, 3 },	/* filtersweights_param0 */
	{ 0x3708, 0x00000000, 149, 3 },	/* filterweights_param1 */
	{ 0x370c, 0x00000000, 152, 3 },	/* filterweights_param2 */
	{ 0x3758, 0x00000000, 155, 0 },	/* tuning_param4 */
	{ 0x375c, 0x00000000, 155, 4 },	/* output_param0 */
	{ 0x3760, 0x00000000, 159, 1 },	/* output_param1 */
	{ 0x3764, 0x00000000, 160, 2 },	/* output_param2 */
	{ 0x3768, 0x00000000, 162, 3 },	/* output_param3 */
	{ 0x376c, 0x00000000, 165, 3 },	/* output_param4 */
	{ 0x3770, 0x00000000, 168, 3 },	/* output_param5 */
	{ 0x3774, 0x00000000, 171, 2 },	/* output_param6 */
	{ 0x3778, 0x00000000, 173, 2 },	/* output_param7 */
	{ 0x377c, 0x00000000, 175, 2 },	/* output_param8 */
	{ 0x3780, 0x00000000, 177, 1 },	/* addhf_gain */
	{ 0x378c, 0x00000000, 178, 2 },	/* hgain_0to1 */
	{ 0x3790, 0x00000000, 180, 2 },	/* hgain_2to3 */
	{ 0x3794, 0x00000000, 182, 2 },	/* hgain_4to5 */
	{ 0x3798, 0x00000000, 184, 2 },	/* hgain_6to7 */
	{ 0x379c, 0x00000000, 186, 1 },	/* hgain_8 */
	{ 0x37a0, 0x00000000, 187, 2 },	/* vgain_0to1 */
	{ 0x37a4, 0x00000000, 189, 2 },	/* vgain_2to3 */
	{ 0x37a8, 0x00000000, 191, 2 },	/* vgain_4to5 */
	{ 0x37ac, 0x00000000, 193, 2 },	/* vgain_6to7 */
	{ 0x37b0, 0x00000000, 195, 1 },	/* vgain_8 */
	{ 0x37b4, 0x00000000, 196, 2 },	/* wide_gain */
	{ 0x37b8, 0x01000100, 198, 5 },	/* hfnr_return_noise_en */
	{ 0x37bc, 0x00000000, 203, 1 },	/* hfnr_return_noise_coring_y */
	{ 0x37c0, 0x00000000, 204, 2 },	/* hfnr_return_noise_coring_uv */
	{ 0x37c4, 0x00000000, 206, 2 },	/* hfnr_return_noise_factor_y */
	{ 0x37c8, 0x00000000, 208, 4 },	/* hfnr_return_noise_factor_uv */
	{ 0x37cc, 0x00000000, 212, 1 },	/* hfnr_return_noise_limit_y */
	{ 0x37d0, 0x00000000, 213, 2 },	/* hfnr_return_noise_limit_uv */
};

static_assert(ARRAY_SIZE(becore_yuvnr_regs) == BECORE_YUVNR_REGS);

/*
 * The same registers as ranges, for the generated table in the driver and for
 * the recipe generator that has to agree with it.
 *
 * The noise curve's own knots are *not* here even though the table encodes
 * them.  The driver resolves them out of the recipe at probe and derives the
 * curve's slopes and shifts from them whenever no parameters block is in
 * force; a generated word reads back as zero, and a domain that does not rise
 * is an arithmetic it refuses.  Twelve words therefore stay replayed until
 * there is a default noise curve to state in their place, and the chroma
 * domain stays BECORE_GEN_NOISE_DOMAIN, which repeats the luma one.
 *
 * A range added here has to stay clear of the one reader of the recipe left,
 * becore_noise_knots_resolve(), which is why the twelve above are held back.
 * The temporal gain curve's knots at +0x33f8..+0x3400 were a second reader
 * until the driver started deriving them from `mcfp_gain_lut_x`; they are not
 * field deposits, so they are still not in this list, and the driver names
 * their range beside the slopes it derives the same way.
 */
#define BECORE_YUVNR_RANGE(first, last)	\
	{ BECORE_YUVP_PHYS_BASE + (first),	\
	  BECORE_YUVP_PHYS_BASE + (last), BECORE_GEN_YUVNR }

#define BECORE_YUVNR_TUNING_RANGES \
	BECORE_YUVNR_RANGE(0x3200, 0x3204), \
	BECORE_YUVNR_RANGE(0x320c, 0x3210), \
	BECORE_YUVNR_RANGE(0x32c8, 0x32c8), \
	BECORE_YUVNR_RANGE(0x32d8, 0x32dc), \
	BECORE_YUVNR_RANGE(0x32ec, 0x32ec), \
	BECORE_YUVNR_RANGE(0x3300, 0x3308), \
	BECORE_YUVNR_RANGE(0x3360, 0x3360), \
	BECORE_YUVNR_RANGE(0x336c, 0x336c), \
	BECORE_YUVNR_RANGE(0x3374, 0x3374), \
	BECORE_YUVNR_RANGE(0x33ec, 0x33ec), \
	BECORE_YUVNR_RANGE(0x3420, 0x3448), \
	BECORE_YUVNR_RANGE(0x351c, 0x351c), \
	BECORE_YUVNR_RANGE(0x3574, 0x35b0), \
	BECORE_YUVNR_RANGE(0x35c4, 0x35c4), \
	BECORE_YUVNR_RANGE(0x35cc, 0x35cc), \
	BECORE_YUVNR_RANGE(0x35d4, 0x35d4), \
	BECORE_YUVNR_RANGE(0x35e4, 0x35e8), \
	BECORE_YUVNR_RANGE(0x3600, 0x3604), \
	BECORE_YUVNR_RANGE(0x3618, 0x361c), \
	BECORE_YUVNR_RANGE(0x3628, 0x362c), \
	BECORE_YUVNR_RANGE(0x3638, 0x363c), \
	BECORE_YUVNR_RANGE(0x3664, 0x3668), \
	BECORE_YUVNR_RANGE(0x3670, 0x3674), \
	BECORE_YUVNR_RANGE(0x367c, 0x367c), \
	BECORE_YUVNR_RANGE(0x36ec, 0x36ec), \
	BECORE_YUVNR_RANGE(0x36f4, 0x36f8), \
	BECORE_YUVNR_RANGE(0x3700, 0x370c), \
	BECORE_YUVNR_RANGE(0x3758, 0x3780), \
	BECORE_YUVNR_RANGE(0x378c, 0x37d0),

#endif /* __EXYNOS_BECORE_YUVNR_H */
