/* SPDX-License-Identifier: GPL-2.0 */
/*
 * BYR_DNS's float-to-register encode.
 *
 * Generated by tools/camera-byrdns-encode.py --c-header; do not edit.
 *
 * Each entry says where one value from struct exynos_becore_params_byr_dns lands:
 * which register, which bits of it, and the range the vendor's own translator
 * clamps it to.  The scale each value is sent at is in the UAPI header beside
 * the member, because that is where userspace reads it.
 *
 * `constant` is what `lyric::TranslateByrDns` deposits in a register whatever
 * the tuning says, so a parameter set of all zeros encodes to exactly these
 * constants -- which, because the block's `enable` reaches its register
 * inverted, is the denoiser bypassed.
 */

#ifndef __EXYNOS_BECORE_BYRDNS_H
#define __EXYNOS_BECORE_BYRDNS_H

/* The value reaches the register inverted: the block's own bypass bit. */
#define BECORE_BYR_DNS_FIELD_INVERT		BIT(0)

/*
 * The value is a white-balance gain and a fixed point away from the register.
 * Green's gain is unity -- the AWB normalises it -- but the fixed point is not,
 * so all three take this path and only the gain differs.
 */
#define BECORE_BYR_DNS_FIELD_RED		BIT(1)
#define BECORE_BYR_DNS_FIELD_GREEN		BIT(2)
#define BECORE_BYR_DNS_FIELD_BLUE		BIT(3)

/**
 * struct becore_byr_dns_field - One value's place in one register
 * @offset: byte offset of the value in struct exynos_becore_params_byr_dns
 * @min: the smallest value the vendor's translator will encode
 * @max: the largest
 * @shift: the bit the field starts at
 * @width: how wide it is
 * @flags: %BECORE_BYR_DNS_FIELD_INVERT and the two balance flags, or zero
 */
struct becore_byr_dns_field {
	u32 offset;
	s32 min;
	s32 max;
	u8 shift;
	u8 width;
	u8 flags;
};

/**
 * struct becore_byr_dns_reg - One register of the block's tuning
 * @offset: the register, from BECORE_RGBP_PHYS_BASE
 * @constant: the bits the translator sets whatever the tuning says
 * @first: where this register's fields start in becore_byr_dns_fields[]
 * @count: how many it has
 */
struct becore_byr_dns_reg {
	u16 offset;
	u32 constant;
	u16 first;
	u8 count;
};

#define BECORE_BYR_DNS_REGS		19
#define BECORE_BYR_DNS_FIELDS		35
#define BECORE_BYR_DNS_VALUES		36

/*
 * The block is a flat sequence of __s32 behind its header, with no padding
 * anywhere in it, which is what lets the offsets below be generated from the
 * header's own member order.  A member added to one and not the other, or a
 * type that brought alignment with it, stops compiling here.
 */
static_assert(sizeof(struct exynos_becore_params_byr_dns) ==
	      sizeof(struct v4l2_isp_params_block_header) +
	      BECORE_BYR_DNS_VALUES * sizeof(__s32));

#define BECORE_BYR_DNS_AT(member)	\
	offsetof(struct exynos_becore_params_byr_dns, member)

static const struct becore_byr_dns_field becore_byr_dns_fields[] = {
	/* +0x3100 bypass [0] x1 */
	{ BECORE_BYR_DNS_AT(enable), 0, 1, 0, 1, BECORE_BYR_DNS_FIELD_INVERT },
	/* +0x3104 controls [10] x1 */
	{ BECORE_BYR_DNS_AT(enable_low_power), 0, 1, 10, 1, 0 },
	/* +0x3120 std_lut_y_g [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[0]), 0, 4095, 0, 12, 0 },
	/* +0x3120 std_lut_y_g [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[1]), 0, 4095, 16, 12, 0 },
	/* +0x3124 std_lut_y_1_g [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[2]), 0, 4095, 0, 12, 0 },
	/* +0x3124 std_lut_y_1_g [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[3]), 0, 4095, 16, 12, 0 },
	/* +0x3128 std_lut_y_2_g [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[4]), 0, 4095, 0, 12, 0 },
	/* +0x3128 std_lut_y_2_g [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[5]), 0, 4095, 16, 12, 0 },
	/* +0x312c std_lut_y_3_g [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[6]), 0, 4095, 0, 12, 0 },
	/* +0x312c std_lut_y_3_g [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_g[7]), 0, 4095, 16, 12, 0 },
	/* +0x3154 std_lut_y_rb [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[0]), 0, 4095, 0, 12, 0 },
	/* +0x3154 std_lut_y_rb [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[1]), 0, 4095, 16, 12, 0 },
	/* +0x3158 std_lut_y_1_rb [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[2]), 0, 4095, 0, 12, 0 },
	/* +0x3158 std_lut_y_1_rb [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[3]), 0, 4095, 16, 12, 0 },
	/* +0x315c std_lut_y_2_rb [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[4]), 0, 4095, 0, 12, 0 },
	/* +0x315c std_lut_y_2_rb [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[5]), 0, 4095, 16, 12, 0 },
	/* +0x3160 std_lut_y_3_rb [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[6]), 0, 4095, 0, 12, 0 },
	/* +0x3160 std_lut_y_3_rb [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_lut_y_rb[7]), 0, 4095, 16, 12, 0 },
	/* +0x3178 std_factors [0] x4096 */
	{ BECORE_BYR_DNS_AT(std_factor_g),
	  0, 63, 0, 6, BECORE_BYR_DNS_FIELD_GREEN },
	/* +0x3178 std_factors [8] x4096 */
	{ BECORE_BYR_DNS_AT(std_factor_r),
	  0, 63, 8, 6, BECORE_BYR_DNS_FIELD_RED },
	/* +0x3178 std_factors [16] x4096 */
	{ BECORE_BYR_DNS_AT(std_factor_b),
	  0, 63, 16, 6, BECORE_BYR_DNS_FIELD_BLUE },
	/* +0x317c lpf_config [0] x1 */
	{ BECORE_BYR_DNS_AT(g_lpf), 0, 7, 0, 3, 0 },
	/* +0x317c lpf_config [8] x1 */
	{ BECORE_BYR_DNS_AT(rb_lpf), 0, 7, 8, 3, 0 },
	/* +0x3184 min_snr_green_config [0] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_pix_number_low_g), 0, 15, 0, 4, 0 },
	/* +0x3184 min_snr_green_config [16] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_pix_number_high_g), 0, 15, 16, 4, 0 },
	/* +0x3188 min_snr_green_bin_width [0] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_bin_width_g), 0, 255, 0, 8, 0 },
	/* +0x3194 min_snr_rb_config [0] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_pix_number_low_rb), 0, 15, 0, 4, 0 },
	/* +0x3194 min_snr_rb_config [16] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_pix_number_high_rb), 0, 15, 16, 4, 0 },
	/* +0x3198 min_snr_rb_bin_width [0] x1 */
	{ BECORE_BYR_DNS_AT(min_snr_bin_width_rb), 0, 255, 0, 8, 0 },
	/* +0x31ac biquad_factor_g [0] x1 */
	{ BECORE_BYR_DNS_AT(biquad_factor_a_g), 0, 1023, 0, 10, 0 },
	/* +0x31ac biquad_factor_g [16] x1 */
	{ BECORE_BYR_DNS_AT(biquad_factor_b_g), 0, 1023, 16, 10, 0 },
	/* +0x31b0 biquad_factor_uv [0] x1 */
	{ BECORE_BYR_DNS_AT(biquad_factor_a_uv), 0, 1023, 0, 10, 0 },
	/* +0x31b0 biquad_factor_uv [16] x1 */
	{ BECORE_BYR_DNS_AT(biquad_factor_b_uv), 0, 1023, 16, 10, 0 },
	/* +0x31bc radial_thresh_limit [0] x1 */
	{ BECORE_BYR_DNS_AT(radial_thresh_limit_g), 0, 1023, 0, 10, 0 },
	/* +0x31bc radial_thresh_limit [16] x1 */
	{ BECORE_BYR_DNS_AT(radial_thresh_limit_rb), 0, 1023, 16, 10, 0 },
};

static_assert(ARRAY_SIZE(becore_byr_dns_fields) == BECORE_BYR_DNS_FIELDS);

static const struct becore_byr_dns_reg becore_byr_dns_regs[] = {
	{ 0x3100, 0x00000000, 0, 1 },	/* bypass */
	{ 0x3104, 0x000008c3, 1, 1 },	/* controls */
	{ 0x3120, 0x00000000, 2, 2 },	/* std_lut_y_g */
	{ 0x3124, 0x00000000, 4, 2 },	/* std_lut_y_1_g */
	{ 0x3128, 0x00000000, 6, 2 },	/* std_lut_y_2_g */
	{ 0x312c, 0x00000000, 8, 2 },	/* std_lut_y_3_g */
	{ 0x3154, 0x00000000, 10, 2 },	/* std_lut_y_rb */
	{ 0x3158, 0x00000000, 12, 2 },	/* std_lut_y_1_rb */
	{ 0x315c, 0x00000000, 14, 2 },	/* std_lut_y_2_rb */
	{ 0x3160, 0x00000000, 16, 2 },	/* std_lut_y_3_rb */
	{ 0x3178, 0x00000000, 18, 3 },	/* std_factors */
	{ 0x317c, 0x00000000, 21, 2 },	/* lpf_config */
	{ 0x3184, 0x00000000, 23, 2 },	/* min_snr_green_config */
	{ 0x3188, 0x00000000, 25, 1 },	/* min_snr_green_bin_width */
	{ 0x3194, 0x00000000, 26, 2 },	/* min_snr_rb_config */
	{ 0x3198, 0x00000000, 28, 1 },	/* min_snr_rb_bin_width */
	{ 0x31ac, 0x00000000, 29, 2 },	/* biquad_factor_g */
	{ 0x31b0, 0x00000000, 31, 2 },	/* biquad_factor_uv */
	{ 0x31bc, 0x00000000, 33, 2 },	/* radial_thresh_limit */
};

static_assert(ARRAY_SIZE(becore_byr_dns_regs) == BECORE_BYR_DNS_REGS);

/*
 * The same registers as ranges, for the generated table in the driver and for
 * the recipe generator that has to agree with it.
 */
#define BECORE_BYR_DNS_RANGE(first, last)	\
	{ BECORE_RGBP_PHYS_BASE + (first),	\
	  BECORE_RGBP_PHYS_BASE + (last), BECORE_GEN_BYR_DNS }

#define BECORE_BYR_DNS_TUNING_RANGES \
	BECORE_BYR_DNS_RANGE(0x3100, 0x3104), \
	BECORE_BYR_DNS_RANGE(0x3120, 0x312c), \
	BECORE_BYR_DNS_RANGE(0x3154, 0x3160), \
	BECORE_BYR_DNS_RANGE(0x3178, 0x317c), \
	BECORE_BYR_DNS_RANGE(0x3184, 0x3188), \
	BECORE_BYR_DNS_RANGE(0x3194, 0x3198), \
	BECORE_BYR_DNS_RANGE(0x31ac, 0x31b0), \
	BECORE_BYR_DNS_RANGE(0x31bc, 0x31bc),

#endif /* __EXYNOS_BECORE_BYRDNS_H */
