/* SPDX-License-Identifier: GPL-2.0 */
/*
 * SHARPENHANCER's float-to-register encode.
 *
 * Generated by tools/camera-sharpener-encode.py --c-header; do not edit.
 *
 * Each entry says where one value from struct exynos_becore_params_sharpen
 * lands: which register, which bits of it, and the range the vendor's own
 * translator clamps it to.  The scale each value is sent at is in the UAPI
 * header beside the member, because that is where userspace reads it; it is
 * repeated in the comments here so that the two can be compared.
 *
 * `constant` is what `lyric::TranslateYuvSharpEnhancer` deposits in a register
 * regardless of the tuning, so a parameter set of all zeros encodes to exactly
 * these constants -- which is what the driver writes underneath a block that
 * has sent nothing.
 */

#ifndef __EXYNOS_BECORE_SHARPEN_H
#define __EXYNOS_BECORE_SHARPEN_H

/**
 * struct becore_sharpen_field - One value's place in one register
 * @offset: byte offset of the value in struct exynos_becore_params_sharpen
 * @min: the smallest value the vendor's translator will encode
 * @max: the largest
 * @shift: the bit the field starts at
 * @width: how wide it is; a field whose @min is negative is two's complement
 */
struct becore_sharpen_field {
	u32 offset;
	s32 min;
	s32 max;
	u8 shift;
	u8 width;
};

/**
 * struct becore_sharpen_reg - One register of the block's tuning
 * @offset: the register, from BECORE_YUVP_PHYS_BASE
 * @constant: the bits the translator sets whatever the tuning says
 * @first: where this register's fields start in becore_sharpen_fields[]
 * @count: how many it has
 */
struct becore_sharpen_reg {
	u16 offset;
	u32 constant;
	u16 first;
	u8 count;
};

#define BECORE_SHARPEN_REGS		145
#define BECORE_SHARPEN_FIELDS		344
#define BECORE_SHARPEN_VALUES		242

/*
 * The block is a flat sequence of __s32 behind its header, with no padding
 * anywhere in it -- which is what lets a payload be written by anything that
 * can count, and what lets the offsets below be generated from the header's
 * own member order.  A member added to one and not the other, or a type that
 * brought alignment with it, stops compiling here rather than in a picture.
 */
static_assert(sizeof(struct exynos_becore_params_sharpen) ==
	      sizeof(struct v4l2_isp_params_block_header) +
	      BECORE_SHARPEN_VALUES * sizeof(__s32));

#define BECORE_SHARPEN_AT(member)	\
	offsetof(struct exynos_becore_params_sharpen, member)

static const struct becore_sharpen_field becore_sharpen_fields[] = {
	/* +0x5004 control [0] x1 */
	{ BECORE_SHARPEN_AT(enable_low_power), 0, 1, 0, 1 },
	/* +0x515c texture_index_0 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_texture_index), 0, 1, 0, 1 },
	/* +0x5174 edge_index [0] x1 */
	{ BECORE_SHARPEN_AT(enable_edge_index), 0, 1, 0, 1 },
	/* +0x5174 edge_index [8] x128 */
	{ BECORE_SHARPEN_AT(edge_index_dir_multiplier), 0, 255, 8, 8 },
	/* +0x5178 gf_sharp_en [0] x1 */
	{ BECORE_SHARPEN_AT(enable_gf_sharp), 0, 1, 0, 1 },
	/* +0x5188 invs_halo [0] x1 */
	{ BECORE_SHARPEN_AT(enable_invs_halo), 0, 1, 0, 1 },
	/* +0x5190 wide_sharp [0] x1 */
	{ BECORE_SHARPEN_AT(enable_wide_sharp), 0, 1, 0, 1 },
	/* +0x5194 wide_sharp_lc_control [0] x1 */
	{ BECORE_SHARPEN_AT(enable_wide_sharp_lc), 0, 1, 0, 1 },
	/* +0x519c wide_sharp_lc [0] x63 */
	{ BECORE_SHARPEN_AT(wide_sharp_lc_simple_power), 0, 63, 0, 6 },
	/* +0x5208 config_1 [15] x1 */
	{ BECORE_SHARPEN_AT(enable_radial_correction), 0, 1, 15, 1 },
	/* +0x5208 config_1 [16] x1 */
	{ BECORE_SHARPEN_AT(enable_radial_correction), 0, 1, 16, 1 },
	/* +0x5208 config_1 [17] x1 */
	{ BECORE_SHARPEN_AT(enable_radial_correction), 0, 1, 17, 1 },
	/* +0x520c medi_edge_thresh_low [0] x1023 */
	{ BECORE_SHARPEN_AT(medium_edge_thresholds.positive_low),
	  0, 1023, 0, 10 },
	/* +0x520c medi_edge_thresh_low [16] x1023 */
	{ BECORE_SHARPEN_AT(medium_edge_thresholds.negative_low),
	  0, 1023, 16, 10 },
	/* +0x5210 medi_edge_thresh_high [0] x1023 */
	{ BECORE_SHARPEN_AT(medium_edge_thresholds.positive_high),
	  0, 1023, 0, 10 },
	/* +0x5210 medi_edge_thresh_high [16] x1023 */
	{ BECORE_SHARPEN_AT(medium_edge_thresholds.negative_high),
	  0, 1023, 16, 10 },
	/* +0x5214 narr_edge_thresh_low [0] x1023 */
	{ BECORE_SHARPEN_AT(narrow_edge_thresholds.positive_low),
	  0, 1023, 0, 10 },
	/* +0x5214 narr_edge_thresh_low [16] x1023 */
	{ BECORE_SHARPEN_AT(narrow_edge_thresholds.negative_low),
	  0, 1023, 16, 10 },
	/* +0x5218 narr_edge_thresh_high [0] x1023 */
	{ BECORE_SHARPEN_AT(narrow_edge_thresholds.positive_high),
	  0, 1023, 0, 10 },
	/* +0x5218 narr_edge_thresh_high [16] x1023 */
	{ BECORE_SHARPEN_AT(narrow_edge_thresholds.negative_high),
	  0, 1023, 16, 10 },
	/* +0x521c medi_txtr_thresh_low [0] x1023 */
	{ BECORE_SHARPEN_AT(medium_texture_thresholds.positive_low),
	  0, 1023, 0, 10 },
	/* +0x521c medi_txtr_thresh_low [16] x1023 */
	{ BECORE_SHARPEN_AT(medium_texture_thresholds.negative_low),
	  0, 1023, 16, 10 },
	/* +0x5220 medi_txtr_thresh_high [0] x1023 */
	{ BECORE_SHARPEN_AT(medium_texture_thresholds.positive_high),
	  0, 1023, 0, 10 },
	/* +0x5220 medi_txtr_thresh_high [16] x1023 */
	{ BECORE_SHARPEN_AT(medium_texture_thresholds.negative_high),
	  0, 1023, 16, 10 },
	/* +0x5224 narr_txtr_thresh_low [0] x1023 */
	{ BECORE_SHARPEN_AT(narrow_texture_thresholds.positive_low),
	  0, 1023, 0, 10 },
	/* +0x5224 narr_txtr_thresh_low [16] x1023 */
	{ BECORE_SHARPEN_AT(narrow_texture_thresholds.negative_low),
	  0, 1023, 16, 10 },
	/* +0x5228 narr_txtr_thresh_high [0] x1023 */
	{ BECORE_SHARPEN_AT(narrow_texture_thresholds.positive_high),
	  0, 1023, 0, 10 },
	/* +0x5228 narr_txtr_thresh_high [16] x1023 */
	{ BECORE_SHARPEN_AT(narrow_texture_thresholds.negative_high),
	  0, 1023, 16, 10 },
	/* +0x522c wmf_edge_limit_2 [0] x255 */
	{ BECORE_SHARPEN_AT(medium_edge_limits.negative_low), 0, 255, 0, 8 },
	/* +0x522c wmf_edge_limit_2 [8] x255 */
	{ BECORE_SHARPEN_AT(medium_edge_limits.negative_high), 0, 255, 8, 8 },
	/* +0x522c wmf_edge_limit_2 [16] x255 */
	{ BECORE_SHARPEN_AT(medium_edge_limits.positive_low), 0, 255, 16, 8 },
	/* +0x522c wmf_edge_limit_2 [24] x255 */
	{ BECORE_SHARPEN_AT(medium_edge_limits.positive_high), 0, 255, 24, 8 },
	/* +0x5230 wmf_edge_limit_3 [0] x255 */
	{ BECORE_SHARPEN_AT(narrow_edge_limits.negative_low), 0, 255, 0, 8 },
	/* +0x5230 wmf_edge_limit_3 [8] x255 */
	{ BECORE_SHARPEN_AT(narrow_edge_limits.negative_high), 0, 255, 8, 8 },
	/* +0x5230 wmf_edge_limit_3 [16] x255 */
	{ BECORE_SHARPEN_AT(narrow_edge_limits.positive_low), 0, 255, 16, 8 },
	/* +0x5230 wmf_edge_limit_3 [24] x255 */
	{ BECORE_SHARPEN_AT(narrow_edge_limits.positive_high), 0, 255, 24, 8 },
	/* +0x5234 wmf_txtr_limit_2 [0] x255 */
	{ BECORE_SHARPEN_AT(medium_texture_limits.negative_low), 0, 255, 0, 8 },
	/* +0x5234 wmf_txtr_limit_2 [8] x255 */
	{ BECORE_SHARPEN_AT(medium_texture_limits.negative_high),
	  0, 255, 8, 8 },
	/* +0x5234 wmf_txtr_limit_2 [16] x255 */
	{ BECORE_SHARPEN_AT(medium_texture_limits.positive_low),
	  0, 255, 16, 8 },
	/* +0x5234 wmf_txtr_limit_2 [24] x255 */
	{ BECORE_SHARPEN_AT(medium_texture_limits.positive_high),
	  0, 255, 24, 8 },
	/* +0x5238 wmf_txtr_limit_3 [0] x255 */
	{ BECORE_SHARPEN_AT(narrow_texture_limits.negative_low), 0, 255, 0, 8 },
	/* +0x5238 wmf_txtr_limit_3 [8] x255 */
	{ BECORE_SHARPEN_AT(narrow_texture_limits.negative_high),
	  0, 255, 8, 8 },
	/* +0x5238 wmf_txtr_limit_3 [16] x255 */
	{ BECORE_SHARPEN_AT(narrow_texture_limits.positive_low),
	  0, 255, 16, 8 },
	/* +0x5238 wmf_txtr_limit_3 [24] x255 */
	{ BECORE_SHARPEN_AT(narrow_texture_limits.positive_high),
	  0, 255, 24, 8 },
	/* +0x524c edge_limit [0] x255 */
	{ BECORE_SHARPEN_AT(edge_limits.negative_low), 0, 255, 0, 8 },
	/* +0x524c edge_limit [8] x255 */
	{ BECORE_SHARPEN_AT(edge_limits.negative_high), 0, 255, 8, 8 },
	/* +0x524c edge_limit [16] x255 */
	{ BECORE_SHARPEN_AT(edge_limits.positive_low), 0, 255, 16, 8 },
	/* +0x524c edge_limit [24] x255 */
	{ BECORE_SHARPEN_AT(edge_limits.positive_high), 0, 255, 24, 8 },
	/* +0x5250 txtr_limit [0] x255 */
	{ BECORE_SHARPEN_AT(texture_limits.negative_low), 0, 255, 0, 8 },
	/* +0x5250 txtr_limit [8] x255 */
	{ BECORE_SHARPEN_AT(texture_limits.negative_high), 0, 255, 8, 8 },
	/* +0x5250 txtr_limit [16] x255 */
	{ BECORE_SHARPEN_AT(texture_limits.positive_low), 0, 255, 16, 8 },
	/* +0x5250 txtr_limit [24] x255 */
	{ BECORE_SHARPEN_AT(texture_limits.positive_high), 0, 255, 24, 8 },
	/* +0x5258 radial_sharp [0] x1023 */
	{ BECORE_SHARPEN_AT(radial_sharp_power), 0, 1023, 0, 10 },
	/* +0x5258 radial_sharp [16] x2048 */
	{ BECORE_SHARPEN_AT(radial_sharp_powers.min), 0, 4095, 16, 12 },
	/* +0x525c radial_sharp_pow_min [0] x2048 */
	{ BECORE_SHARPEN_AT(radial_sharp_powers.min), 0, 4095, 0, 12 },
	/* +0x5260 gf_sharp_thresh_low [0] x1023 */
	{ BECORE_SHARPEN_AT(texture_gf_thresholds.positive_low),
	  0, 1023, 0, 10 },
	/* +0x5260 gf_sharp_thresh_low [16] x1023 */
	{ BECORE_SHARPEN_AT(texture_gf_thresholds.negative_low),
	  0, 1023, 16, 10 },
	/* +0x5264 gf_sharp_thresh_high [0] x1023 */
	{ BECORE_SHARPEN_AT(texture_gf_thresholds.positive_high),
	  0, 1023, 0, 10 },
	/* +0x5264 gf_sharp_thresh_high [16] x1023 */
	{ BECORE_SHARPEN_AT(texture_gf_thresholds.negative_high),
	  0, 1023, 16, 10 },
	/* +0x527c gf_sharp_power_total_gain_0_to_1 [0] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[0]),
	  0, 1023, 0, 10 },
	/* +0x527c gf_sharp_power_total_gain_0_to_1 [16] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[1]),
	  0, 1023, 16, 10 },
	/* +0x5280 gf_sharp_power_total_gain_2_to_3 [0] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[2]),
	  0, 1023, 0, 10 },
	/* +0x5280 gf_sharp_power_total_gain_2_to_3 [16] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[3]),
	  0, 1023, 16, 10 },
	/* +0x5284 gf_sharp_power_total_gain_4_to_5 [0] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[4]),
	  0, 1023, 0, 10 },
	/* +0x5284 gf_sharp_power_total_gain_4_to_5 [16] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[5]),
	  0, 1023, 16, 10 },
	/* +0x5288 gf_sharp_power_total_gain_6_to_7 [0] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[6]),
	  0, 1023, 0, 10 },
	/* +0x5288 gf_sharp_power_total_gain_6_to_7 [16] x128 */
	{ BECORE_SHARPEN_AT(texture_gf_sharp_power_gain_lut[7]),
	  0, 1023, 16, 10 },
	/* +0x528c gf_sharp_limit [0] x255 */
	{ BECORE_SHARPEN_AT(texture_gf_limits.negative_low), 0, 255, 0, 8 },
	/* +0x528c gf_sharp_limit [8] x255 */
	{ BECORE_SHARPEN_AT(texture_gf_limits.negative_high), 0, 255, 8, 8 },
	/* +0x528c gf_sharp_limit [16] x255 */
	{ BECORE_SHARPEN_AT(texture_gf_limits.positive_low), 0, 255, 16, 8 },
	/* +0x528c gf_sharp_limit [24] x255 */
	{ BECORE_SHARPEN_AT(texture_gf_limits.positive_high), 0, 255, 24, 8 },
	/* +0x52b4 medi_edge_power_total_gain_0_to_1 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[0]),
	  0, 1023, 0, 10 },
	/* +0x52b4 medi_edge_power_total_gain_0_to_1 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[1]),
	  0, 1023, 16, 10 },
	/* +0x52b8 medi_edge_power_total_gain_2_to_3 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[2]),
	  0, 1023, 0, 10 },
	/* +0x52b8 medi_edge_power_total_gain_2_to_3 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[3]),
	  0, 1023, 16, 10 },
	/* +0x52bc medi_edge_power_total_gain_4_to_5 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[4]),
	  0, 1023, 0, 10 },
	/* +0x52bc medi_edge_power_total_gain_4_to_5 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[5]),
	  0, 1023, 16, 10 },
	/* +0x52c0 medi_edge_power_total_gain_6_to_7 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[6]),
	  0, 1023, 0, 10 },
	/* +0x52c0 medi_edge_power_total_gain_6_to_7 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_edge_sharp_power_gain_lut[7]),
	  0, 1023, 16, 10 },
	/* +0x52c4 narr_edge_power_total_gain_0_to_1 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[0]),
	  0, 1023, 0, 10 },
	/* +0x52c4 narr_edge_power_total_gain_0_to_1 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[1]),
	  0, 1023, 16, 10 },
	/* +0x52c8 narr_edge_power_total_gain_2_to_3 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[2]),
	  0, 1023, 0, 10 },
	/* +0x52c8 narr_edge_power_total_gain_2_to_3 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[3]),
	  0, 1023, 16, 10 },
	/* +0x52cc narr_edge_power_total_gain_4_to_5 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[4]),
	  0, 1023, 0, 10 },
	/* +0x52cc narr_edge_power_total_gain_4_to_5 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[5]),
	  0, 1023, 16, 10 },
	/* +0x52d0 narr_edge_power_total_gain_6_to_7 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[6]),
	  0, 1023, 0, 10 },
	/* +0x52d0 narr_edge_power_total_gain_6_to_7 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_edge_sharp_power_gain_lut[7]),
	  0, 1023, 16, 10 },
	/* +0x52e4 medi_txtr_power_total_gain_0_to_1 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[0]),
	  0, 1023, 0, 10 },
	/* +0x52e4 medi_txtr_power_total_gain_0_to_1 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[1]),
	  0, 1023, 16, 10 },
	/* +0x52e8 medi_txtr_power_total_gain_2_to_3 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[2]),
	  0, 1023, 0, 10 },
	/* +0x52e8 medi_txtr_power_total_gain_2_to_3 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[3]),
	  0, 1023, 16, 10 },
	/* +0x52ec medi_txtr_power_total_gain_4_to_5 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[4]),
	  0, 1023, 0, 10 },
	/* +0x52ec medi_txtr_power_total_gain_4_to_5 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[5]),
	  0, 1023, 16, 10 },
	/* +0x52f0 medi_txtr_power_total_gain_6_to_7 [0] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[6]),
	  0, 1023, 0, 10 },
	/* +0x52f0 medi_txtr_power_total_gain_6_to_7 [16] x128 */
	{ BECORE_SHARPEN_AT(medium_texture_sharp_power_gain_lut[7]),
	  0, 1023, 16, 10 },
	/* +0x52f4 narr_txtr_power_total_gain_0_to_1 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[0]),
	  0, 1023, 0, 10 },
	/* +0x52f4 narr_txtr_power_total_gain_0_to_1 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[1]),
	  0, 1023, 16, 10 },
	/* +0x52f8 narr_txtr_power_total_gain_2_to_3 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[2]),
	  0, 1023, 0, 10 },
	/* +0x52f8 narr_txtr_power_total_gain_2_to_3 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[3]),
	  0, 1023, 16, 10 },
	/* +0x52fc narr_txtr_power_total_gain_4_to_5 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[4]),
	  0, 1023, 0, 10 },
	/* +0x52fc narr_txtr_power_total_gain_4_to_5 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[5]),
	  0, 1023, 16, 10 },
	/* +0x5300 narr_txtr_power_total_gain_6_to_7 [0] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[6]),
	  0, 1023, 0, 10 },
	/* +0x5300 narr_txtr_power_total_gain_6_to_7 [16] x128 */
	{ BECORE_SHARPEN_AT(narrow_texture_sharp_power_gain_lut[7]),
	  0, 1023, 16, 10 },
	/* +0x5318 sharp_gain [0] x1 */
	{ BECORE_SHARPEN_AT(enable_edge_gain), 0, 1, 0, 1 },
	/* +0x5318 sharp_gain [1] x1 */
	{ BECORE_SHARPEN_AT(enable_texture_gain), 0, 1, 1, 1 },
	/* +0x5318 sharp_gain [2] x255 */
	{ BECORE_SHARPEN_AT(edge_gain_for_flat), 0, 255, 2, 8 },
	/* +0x5318 sharp_gain [16] x511 */
	{ BECORE_SHARPEN_AT(edge_gain_for_edge), 0, 511, 16, 9 },
	/* +0x531c sharp_gain_1 [0] x255 */
	{ BECORE_SHARPEN_AT(texture_gain_for_flat), 0, 255, 0, 8 },
	/* +0x531c sharp_gain_1 [8] x511 */
	{ BECORE_SHARPEN_AT(texture_gain_for_texture), 0, 511, 8, 9 },
	/* +0x5320 invs_halo_grade [0] x1023 */
	{ BECORE_SHARPEN_AT(invs_halo_grade_offset), -1023, 1023, 0, 11 },
	/* +0x5324 invs_halo_texture_weight_offset [0] x1023 */
	{ BECORE_SHARPEN_AT(invs_halo_texture_weight_offsets.negative),
	  -1023, 1023, 0, 11 },
	/* +0x5324 invs_halo_texture_weight_offset [16] x1023 */
	{ BECORE_SHARPEN_AT(invs_halo_texture_weight_offsets.positive),
	  -1023, 1023, 16, 11 },
	/* +0x5334 wsharp_power [0] x255 */
	{ BECORE_SHARPEN_AT(wide_edge_sharp_powers.dark), 0, 255, 0, 8 },
	/* +0x5334 wsharp_power [8] x255 */
	{ BECORE_SHARPEN_AT(wide_edge_sharp_powers.bright), 0, 255, 8, 8 },
	/* +0x5334 wsharp_power [16] x255 */
	{ BECORE_SHARPEN_AT(wide_texture_sharp_powers.dark), 0, 255, 16, 8 },
	/* +0x5334 wsharp_power [24] x255 */
	{ BECORE_SHARPEN_AT(wide_texture_sharp_powers.bright), 0, 255, 24, 8 },
	/* +0x5600 config2 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 4, 1 },
	/* +0x5600 config2 [8] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 8, 1 },
	/* +0x5600 config2 [12] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 12, 1 },
	/* +0x5604 noise_gen_gain [0] x16 */
	{ BECORE_SHARPEN_AT(noise_gains.narrow), 0, 16, 0, 5 },
	/* +0x5604 noise_gen_gain [8] x16 */
	{ BECORE_SHARPEN_AT(noise_gains.medium), 0, 16, 8, 5 },
	/* +0x5604 noise_gen_gain [16] x16 */
	{ BECORE_SHARPEN_AT(noise_gains.wide), 0, 16, 16, 5 },
	/* +0x5608 noise_gen_gain_shift [0] x11 */
	{ BECORE_SHARPEN_AT(noise_shifts.narrow), 0, 11, 0, 4 },
	/* +0x5608 noise_gen_gain_shift [8] x11 */
	{ BECORE_SHARPEN_AT(noise_shifts.medium), 0, 11, 8, 4 },
	/* +0x5608 noise_gen_gain_shift [16] x11 */
	{ BECORE_SHARPEN_AT(noise_shifts.wide), 0, 11, 16, 4 },
	/* +0x5700 noise_gain [0] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 0, 1 },
	/* +0x5700 noise_gain [1] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 1, 1 },
	/* +0x5700 noise_gain [2] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 2, 1 },
	/* +0x5704 noise_gain_1 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_narrow_gains.flat), 0, 255, 0, 8 },
	/* +0x5704 noise_gain_1 [8] x128 */
	{ BECORE_SHARPEN_AT(noise_narrow_gains.edge), 0, 511, 8, 9 },
	/* +0x5704 noise_gain_1 [18] x128 */
	{ BECORE_SHARPEN_AT(noise_narrow_gains.texture), 0, 511, 18, 9 },
	/* +0x5708 noise_gain_2 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_medium_gains.flat), 0, 255, 0, 8 },
	/* +0x5708 noise_gain_2 [8] x128 */
	{ BECORE_SHARPEN_AT(noise_medium_gains.edge), 0, 511, 8, 9 },
	/* +0x5708 noise_gain_2 [18] x128 */
	{ BECORE_SHARPEN_AT(noise_medium_gains.texture), 0, 511, 18, 9 },
	/* +0x570c noise_gain_3 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_wide_gains.flat), 0, 255, 0, 8 },
	/* +0x570c noise_gain_3 [8] x128 */
	{ BECORE_SHARPEN_AT(noise_wide_gains.edge), 0, 511, 8, 9 },
	/* +0x570c noise_gain_3 [18] x128 */
	{ BECORE_SHARPEN_AT(noise_wide_gains.texture), 0, 511, 18, 9 },
	/* +0x5720 noise_gain_lut_total_gain [0] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[0]), 0, 255, 0, 8 },
	/* +0x5720 noise_gain_lut_total_gain [16] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[1]), 0, 255, 16, 8 },
	/* +0x5724 noise_gain_lut_total_gain_1 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[2]), 0, 255, 0, 8 },
	/* +0x5724 noise_gain_lut_total_gain_1 [16] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[3]), 0, 255, 16, 8 },
	/* +0x5728 noise_gain_lut_total_gain_2 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[4]), 0, 255, 0, 8 },
	/* +0x5728 noise_gain_lut_total_gain_2 [16] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[5]), 0, 255, 16, 8 },
	/* +0x572c noise_gain_lut_total_gain_3 [0] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[6]), 0, 255, 0, 8 },
	/* +0x572c noise_gain_lut_total_gain_3 [16] x128 */
	{ BECORE_SHARPEN_AT(noise_gain_lut[7]), 0, 255, 16, 8 },
	/* +0x5730 config_en [18] x1 */
	{ BECORE_SHARPEN_AT(enable_noise_radial_correction), 0, 1, 18, 1 },
	/* +0x5730 config_en [19] x1 */
	{ BECORE_SHARPEN_AT(enable_noise_radial_correction), 0, 1, 19, 1 },
	/* +0x5730 config_en [20] x1 */
	{ BECORE_SHARPEN_AT(enable_noise_radial_correction), 0, 1, 20, 1 },
	/* +0x5730 config_en [24] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 24, 1 },
	/* +0x5734 radial_noise [0] x511 */
	{ BECORE_SHARPEN_AT(noise_radial_power), -511, 511, 0, 10 },
	/* +0x5734 radial_noise [16] x2048 */
	{ BECORE_SHARPEN_AT(noise_radial_powers.max), 0, 4095, 16, 12 },
	/* +0x5738 radial_noise_pow_min [16] x2048 */
	{ BECORE_SHARPEN_AT(noise_radial_powers.min), 0, 4095, 16, 12 },
	/* +0x5800 control_config [0] x1 */
	{ BECORE_SHARPEN_AT(enable_content_detector), 0, 1, 0, 1 },
	/* +0x5800 control_config [1] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 1, 1 },
	/* +0x5800 control_config [3] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 3, 1 },
	/* +0x5800 control_config [4] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 4, 1 },
	/* +0x5800 control_config [5] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 5, 1 },
	/* +0x5800 control_config [6] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 6, 1 },
	/* +0x5800 control_config [8] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 8, 1 },
	/* +0x5800 control_config [9] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 9, 1 },
	/* +0x5800 control_config [10] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 10, 1 },
	/* +0x5800 control_config [11] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 11, 1 },
	/* +0x5800 control_config [13] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 13, 1 },
	/* +0x5800 control_config [14] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 14, 1 },
	/* +0x5800 control_config [15] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 15, 1 },
	/* +0x5800 control_config [16] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 16, 1 },
	/* +0x5800 control_config [18] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 18, 1 },
	/* +0x5800 control_config [19] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 19, 1 },
	/* +0x5800 control_config [20] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 20, 1 },
	/* +0x5800 control_config [21] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 21, 1 },
	/* +0x5800 control_config [23] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 23, 1 },
	/* +0x5800 control_config [24] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 24, 1 },
	/* +0x5800 control_config [25] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 25, 1 },
	/* +0x5824 hue_range_0 [0] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_min.skin), -768, 768, 0, 11 },
	/* +0x5824 hue_range_0 [16] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_max.skin), 0, 768, 16, 10 },
	/* +0x5828 sat_range_0 [0] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_min.skin), 0, 1023, 0, 10 },
	/* +0x5828 sat_range_0 [16] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_max.skin), 0, 1023, 16, 10 },
	/* +0x582c val_range_0 [0] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_min.skin), 0, 2045, 0, 11 },
	/* +0x582c val_range_0 [16] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_max.skin), 0, 2045, 16, 11 },
	/* +0x5834 hue_range_1 [0] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_min.skinb), -768, 768, 0, 11 },
	/* +0x5834 hue_range_1 [16] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_max.skinb), 0, 768, 16, 10 },
	/* +0x5838 sat_range_1 [0] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_min.skinb), 0, 1023, 0, 10 },
	/* +0x5838 sat_range_1 [16] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_max.skinb), 0, 1023, 16, 10 },
	/* +0x583c val_range_1 [0] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_min.skinb), 0, 2045, 0, 11 },
	/* +0x583c val_range_1 [16] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_max.skinb), 0, 2045, 16, 11 },
	/* +0x5844 hue_range_2 [0] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_min.sky), -768, 768, 0, 11 },
	/* +0x5844 hue_range_2 [16] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_max.sky), 0, 768, 16, 10 },
	/* +0x5848 sat_range_2 [0] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_min.sky), 0, 1023, 0, 10 },
	/* +0x5848 sat_range_2 [16] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_max.sky), 0, 1023, 16, 10 },
	/* +0x584c val_range_2 [0] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_min.sky), 0, 2045, 0, 11 },
	/* +0x584c val_range_2 [16] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_max.sky), 0, 2045, 16, 11 },
	/* +0x5854 hue_range_3 [0] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_min.grass), -768, 768, 0, 11 },
	/* +0x5854 hue_range_3 [16] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_max.grass), 0, 768, 16, 10 },
	/* +0x5858 sat_range_3 [0] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_min.grass), 0, 1023, 0, 10 },
	/* +0x5858 sat_range_3 [16] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_max.grass), 0, 1023, 16, 10 },
	/* +0x585c val_range_3 [0] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_min.grass), 0, 2045, 0, 11 },
	/* +0x585c val_range_3 [16] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_max.grass), 0, 2045, 16, 11 },
	/* +0x5864 hue_range_4 [0] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_min.extra), -768, 768, 0, 11 },
	/* +0x5864 hue_range_4 [16] x768 */
	{ BECORE_SHARPEN_AT(content_hsv_hue_max.extra), 0, 768, 16, 10 },
	/* +0x5868 sat_range_4 [0] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_min.extra), 0, 1023, 0, 10 },
	/* +0x5868 sat_range_4 [16] x1023 */
	{ BECORE_SHARPEN_AT(content_hsv_sat_max.extra), 0, 1023, 16, 10 },
	/* +0x586c val_range_4 [0] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_min.extra), 0, 2045, 0, 11 },
	/* +0x586c val_range_4 [16] x2045 */
	{ BECORE_SHARPEN_AT(content_hsv_val_max.extra), 0, 2045, 16, 11 },
	/* +0x5888 desat_1 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_gray), 0, 1, 0, 1 },
	/* +0x5888 desat_1 [1] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_gray), 0, 1, 1, 1 },
	/* +0x5888 desat_1 [2] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_edge), 0, 1, 2, 1 },
	/* +0x5888 desat_1 [3] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_edge), 0, 1, 3, 1 },
	/* +0x5888 desat_1 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_edge), 0, 1, 4, 1 },
	/* +0x5888 desat_1 [5] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_gray), 0, 1, 5, 1 },
	/* +0x5888 desat_1 [6] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_edge), 0, 1, 6, 1 },
	/* +0x588c desat_2 [0] x1023 */
	{ BECORE_SHARPEN_AT(desat_gray_sat_min), 0, 1023, 0, 10 },
	/* +0x588c desat_2 [16] x2045 */
	{ BECORE_SHARPEN_AT(desat_gray_val_min), 0, 2045, 16, 11 },
	/* +0x5890 desat_3 [0] x8 */
	{ BECORE_SHARPEN_AT(desat_gray_s_smooth_shift), 0, 8, 0, 4 },
	/* +0x5890 desat_3 [4] x8 */
	{ BECORE_SHARPEN_AT(desat_gray_s_level_shift), 0, 8, 4, 4 },
	/* +0x5890 desat_3 [8] x8 */
	{ BECORE_SHARPEN_AT(desat_gray_v_smooth_shift), 0, 8, 8, 4 },
	/* +0x5890 desat_3 [12] x8 */
	{ BECORE_SHARPEN_AT(desat_gray_v_level_shift), 0, 8, 12, 4 },
	/* +0x5894 desat_4 [0] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_mins[0]), -768, 768, 0, 11 },
	/* +0x5894 desat_4 [16] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_maxs[0]), 0, 768, 16, 10 },
	/* +0x5898 desat_5 [0] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_mins[1]), -768, 768, 0, 11 },
	/* +0x5898 desat_5 [16] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_maxs[1]), 0, 768, 16, 10 },
	/* +0x589c desat_6 [0] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_mins[2]), -768, 768, 0, 11 },
	/* +0x589c desat_6 [16] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_maxs[2]), 0, 768, 16, 10 },
	/* +0x58a0 desat_7 [0] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_mins[3]), -768, 768, 0, 11 },
	/* +0x58a0 desat_7 [16] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_maxs[3]), 0, 768, 16, 10 },
	/* +0x58a4 desat_8 [0] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_mins[4]), -768, 768, 0, 11 },
	/* +0x58a4 desat_8 [16] x768 */
	{ BECORE_SHARPEN_AT(desat_edge_hue_maxs[4]), 0, 768, 16, 10 },
	/* +0x58a8 desat_9 [0] x1023 */
	{ BECORE_SHARPEN_AT(desat_edge_sats.min), 0, 1023, 0, 10 },
	/* +0x58a8 desat_9 [16] x1023 */
	{ BECORE_SHARPEN_AT(desat_edge_sats.max), 0, 1023, 16, 10 },
	/* +0x58ac desat_10 [0] x2045 */
	{ BECORE_SHARPEN_AT(desat_edge_vals.min), 0, 2045, 0, 11 },
	/* +0x58ac desat_10 [16] x2045 */
	{ BECORE_SHARPEN_AT(desat_edge_vals.max), 0, 2045, 16, 11 },
	/* +0x58b0 desat_11 [0] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_h_smooth_shift), 0, 8, 0, 4 },
	/* +0x58b0 desat_11 [4] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_h_level_shift), 0, 8, 4, 4 },
	/* +0x58b0 desat_11 [8] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_s_smooth_shift), 0, 8, 8, 4 },
	/* +0x58b0 desat_11 [12] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_s_level_shift), 0, 8, 12, 4 },
	/* +0x58b0 desat_11 [16] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_v_smooth_shift), 0, 8, 16, 4 },
	/* +0x58b0 desat_11 [20] x8 */
	{ BECORE_SHARPEN_AT(desat_edge_v_level_shift), 0, 8, 20, 4 },
	/* +0x5900 rgb_sharp_adder_config [24] x1 */
	{ BECORE_SHARPEN_AT(enable_noise), 0, 1, 24, 1 },
	/* +0x590c noise_power [0] x8 */
	{ BECORE_SHARPEN_AT(noise_power), 0, 32, 0, 6 },
	/* +0x5910 content_dependent_config1 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 4, 1 },
	/* +0x5910 content_dependent_config1 [8] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 8, 1 },
	/* +0x5910 content_dependent_config1 [12] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 12, 1 },
	/* +0x5910 content_dependent_config1 [16] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 16, 1 },
	/* +0x5910 content_dependent_config1 [28] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 28, 1 },
	/* +0x5914 content_dependent_config2 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 0, 1 },
	/* +0x5914 content_dependent_config2 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 4, 1 },
	/* +0x5918 content_for_skin [0] x63 */
	{ BECORE_SHARPEN_AT(content_skin_thresholds.texture), 0, 63, 0, 6 },
	/* +0x5918 content_for_skin [16] x63 */
	{ BECORE_SHARPEN_AT(content_skin_thresholds.edge), 0, 63, 16, 6 },
	/* +0x591c action_on_skin [0] x32 */
	{ BECORE_SHARPEN_AT(content_skin.sharpening), -32, 32, 0, 7 },
	/* +0x591c action_on_skin [8] x32 */
	{ BECORE_SHARPEN_AT(content_skin.noise), -32, 32, 8, 7 },
	/* +0x591c action_on_skin [16] x63 */
	{ BECORE_SHARPEN_AT(content_skinb_thresholds.texture), 0, 63, 16, 6 },
	/* +0x5920 action_on_skin_1 [0] x63 */
	{ BECORE_SHARPEN_AT(content_skinb_thresholds.edge), 0, 63, 0, 6 },
	/* +0x5920 action_on_skin_1 [16] x32 */
	{ BECORE_SHARPEN_AT(content_skinb.sharpening), -32, 32, 16, 7 },
	/* +0x5924 content_dependent_cont_config1 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 0, 1 },
	/* +0x5924 content_dependent_cont_config1 [8] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 8, 1 },
	/* +0x5924 content_dependent_cont_config1 [12] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 12, 1 },
	/* +0x5924 content_dependent_cont_config1 [16] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 16, 1 },
	/* +0x5924 content_dependent_cont_config1 [20] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 20, 1 },
	/* +0x5924 content_dependent_cont_config1 [28] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 28, 1 },
	/* +0x5928 content_dependent_cont_config2 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 0, 1 },
	/* +0x5928 content_dependent_cont_config2 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 4, 1 },
	/* +0x5928 content_dependent_cont_config2 [8] x1 */
	{ BECORE_SHARPEN_AT(enable_content_grass), 0, 1, 8, 1 },
	/* +0x5928 content_dependent_cont_config2 [16] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 16, 1 },
	/* +0x5928 content_dependent_cont_config2 [20] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 20, 1 },
	/* +0x5928 content_dependent_cont_config2 [24] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 24, 1 },
	/* +0x5928 content_dependent_cont_config2 [28] x1 */
	{ BECORE_SHARPEN_AT(enable_content_extra), 0, 1, 28, 1 },
	/* +0x592c content_dependent_cont_config3 [0] x1 */
	{ BECORE_SHARPEN_AT(enable_content_sky), 0, 1, 0, 1 },
	/* +0x592c content_dependent_cont_config3 [4] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skin), 0, 1, 4, 1 },
	/* +0x592c content_dependent_cont_config3 [8] x1 */
	{ BECORE_SHARPEN_AT(enable_content_skinb), 0, 1, 8, 1 },
	/* +0x592c content_dependent_cont_config3 [12] x1 */
	{ BECORE_SHARPEN_AT(enable_face_beautification), 0, 1, 12, 1 },
	/* +0x592c content_dependent_cont_config3 [16] x1 */
	{ BECORE_SHARPEN_AT(enable_face_beautification_sharp), 0, 1, 16, 1 },
	/* +0x592c content_dependent_cont_config3 [20] x1 */
	{ BECORE_SHARPEN_AT(enable_face_beautification_noise), 0, 1, 20, 1 },
	/* +0x592c content_dependent_cont_config3 [24] x1 */
	{ BECORE_SHARPEN_AT(enable_face_beautification_brightness),
	  0, 1, 24, 1 },
	/* +0x5934 skin_b_reduce_noise [0] x32 */
	{ BECORE_SHARPEN_AT(content_skinb.noise), -32, 32, 0, 7 },
	/* +0x5938 content_for_sky [0] x63 */
	{ BECORE_SHARPEN_AT(content_sky_thresholds.texture), 0, 63, 0, 6 },
	/* +0x5938 content_for_sky [16] x63 */
	{ BECORE_SHARPEN_AT(content_sky_thresholds.edge), 0, 63, 16, 6 },
	/* +0x593c action_on_sky [0] x32 */
	{ BECORE_SHARPEN_AT(content_sky.sharpening), 0, 32, 0, 6 },
	/* +0x593c action_on_sky [8] x32 */
	{ BECORE_SHARPEN_AT(content_sky.noise), 0, 32, 8, 6 },
	/* +0x5940 content_for_grass [0] x63 */
	{ BECORE_SHARPEN_AT(content_grass_thresholds.texture), 0, 63, 0, 6 },
	/* +0x5940 content_for_grass [16] x63 */
	{ BECORE_SHARPEN_AT(content_grass_thresholds.edge), 0, 63, 16, 6 },
	/* +0x5944 action_on_grass [0] x8 */
	{ BECORE_SHARPEN_AT(content_grass.sharpening), 0, 32, 0, 6 },
	/* +0x5944 action_on_grass [8] x8 */
	{ BECORE_SHARPEN_AT(content_grass.noise), 0, 32, 8, 6 },
	/* +0x5948 content_for_extra [0] x63 */
	{ BECORE_SHARPEN_AT(content_extra_thresholds.texture), 0, 63, 0, 6 },
	/* +0x5948 content_for_extra [16] x63 */
	{ BECORE_SHARPEN_AT(content_extra_thresholds.edge), 0, 63, 16, 6 },
	/* +0x594c action_on_extra [0] x8 */
	{ BECORE_SHARPEN_AT(content_extra.sharpening), 0, 32, 0, 6 },
	/* +0x594c action_on_extra [8] x8 */
	{ BECORE_SHARPEN_AT(content_extra.noise), 0, 32, 8, 6 },
	/* +0x5954 skin_face_brightness_gain [0] x1024 */
	{ BECORE_SHARPEN_AT(face_brightness_gain), 0, 1024, 0, 11 },
	/* +0x59cc face_sharp_level [0] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 0, 7 },
	/* +0x59cc face_sharp_level [8] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 8, 7 },
	/* +0x59cc face_sharp_level [16] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 16, 7 },
	/* +0x59cc face_sharp_level [24] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 24, 7 },
	/* +0x59d0 face_sharp_level_1 [0] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 0, 7 },
	/* +0x59d0 face_sharp_level_1 [8] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 8, 7 },
	/* +0x59d0 face_sharp_level_1 [16] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 16, 7 },
	/* +0x59d0 face_sharp_level_1 [24] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 24, 7 },
	/* +0x59d4 face_sharp_level_2 [0] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 0, 7 },
	/* +0x59d4 face_sharp_level_2 [8] x32 */
	{ BECORE_SHARPEN_AT(face_sharp_level), -32, 32, 8, 7 },
	/* +0x59d8 face_noise_level [0] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 0, 7 },
	/* +0x59d8 face_noise_level [8] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 8, 7 },
	/* +0x59d8 face_noise_level [16] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 16, 7 },
	/* +0x59d8 face_noise_level [24] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 24, 7 },
	/* +0x59dc face_noise_level_1 [0] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 0, 7 },
	/* +0x59dc face_noise_level_1 [8] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 8, 7 },
	/* +0x59dc face_noise_level_1 [16] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 16, 7 },
	/* +0x59dc face_noise_level_1 [24] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 24, 7 },
	/* +0x59e0 face_noise_level_2 [0] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 0, 7 },
	/* +0x59e0 face_noise_level_2 [8] x32 */
	{ BECORE_SHARPEN_AT(face_noise_level), -32, 32, 8, 7 },
	/* +0x59e4 face_brightness_level [0] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 0, 6 },
	/* +0x59e4 face_brightness_level [8] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 8, 6 },
	/* +0x59e4 face_brightness_level [16] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 16, 6 },
	/* +0x59e4 face_brightness_level [24] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 24, 6 },
	/* +0x59e8 face_brightness_level_1 [0] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 0, 6 },
	/* +0x59e8 face_brightness_level_1 [8] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 8, 6 },
	/* +0x59e8 face_brightness_level_1 [16] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 16, 6 },
	/* +0x59e8 face_brightness_level_1 [24] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 24, 6 },
	/* +0x59ec face_brightness_level_2 [0] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 0, 6 },
	/* +0x59ec face_brightness_level_2 [8] x32 */
	{ BECORE_SHARPEN_AT(face_brightness_level), 0, 32, 8, 6 },
	/* +0x5a48 invs_x_i_0 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a4c invs_x_i_1 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a50 invs_x_i_2 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a54 invs_x_i_3 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a58 invs_x_i_4 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a5c invs_x_i_5 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a60 invs_x_i_6 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a64 invs_x_i_7 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a68 invs_x_i_8 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a6c invs_x_i_9 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a70 invs_y_i_0 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a74 invs_y_i_1 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a78 invs_y_i_2 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a7c invs_y_i_3 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a80 invs_y_i_4 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a84 invs_y_i_5 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a88 invs_y_i_6 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a8c invs_y_i_7 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a90 invs_y_i_8 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a94 invs_y_i_9 [0] x1048575 */
	{ BECORE_SHARPEN_AT(radial_face_margin_gain), 0, 1048575, 0, 20 },
	/* +0x5a98 desat_config [0] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_gray), 0, 1, 0, 1 },
	/* +0x5a98 desat_config [1] x1 */
	{ BECORE_SHARPEN_AT(enable_desat_edge), 0, 1, 1, 1 },
	/* +0x5a9c apply_desat_0 [0] x1023 */
	{ BECORE_SHARPEN_AT(desat_gray_threshold), 0, 1023, 0, 10 },
	/* +0x5a9c apply_desat_0 [16] x1023 */
	{ BECORE_SHARPEN_AT(desat_edge_threshold), 0, 1023, 16, 10 },
	/* +0x5aa0 apply_desat_1 [0] x1023 */
	{ BECORE_SHARPEN_AT(desat_gray_min), 0, 1023, 0, 10 },
	/* +0x5aa0 apply_desat_1 [16] x1023 */
	{ BECORE_SHARPEN_AT(desat_edge_min), 0, 1023, 16, 10 },
	/* +0x5aa4 apply_desat_2 [0] x10 */
	{ BECORE_SHARPEN_AT(desat_gray_slope), 0, 10, 0, 4 },
	/* +0x5aa4 apply_desat_2 [4] x10 */
	{ BECORE_SHARPEN_AT(desat_edge_slope), 0, 10, 4, 4 },
};

static_assert(ARRAY_SIZE(becore_sharpen_fields) == BECORE_SHARPEN_FIELDS);

static const struct becore_sharpen_reg becore_sharpen_regs[] = {
	{ 0x5004, 0x00000000, 0, 1 },	/* control */
	{ 0x515c, 0x00200202, 1, 1 },	/* texture_index_0 */
	{ 0x5174, 0x00000000, 2, 2 },	/* edge_index */
	{ 0x5178, 0x00000000, 4, 1 },	/* gf_sharp_en */
	{ 0x5188, 0x00000000, 5, 1 },	/* invs_halo */
	{ 0x5190, 0x00000000, 6, 1 },	/* wide_sharp */
	{ 0x5194, 0x00000100, 7, 1 },	/* wide_sharp_lc_control */
	{ 0x519c, 0x00000000, 8, 1 },	/* wide_sharp_lc */
	{ 0x5208, 0x00007f80, 9, 3 },	/* config_1 */
	{ 0x520c, 0x00000000, 12, 2 },	/* medi_edge_thresh_low */
	{ 0x5210, 0x00000000, 14, 2 },	/* medi_edge_thresh_high */
	{ 0x5214, 0x00000000, 16, 2 },	/* narr_edge_thresh_low */
	{ 0x5218, 0x00000000, 18, 2 },	/* narr_edge_thresh_high */
	{ 0x521c, 0x00000000, 20, 2 },	/* medi_txtr_thresh_low */
	{ 0x5220, 0x00000000, 22, 2 },	/* medi_txtr_thresh_high */
	{ 0x5224, 0x00000000, 24, 2 },	/* narr_txtr_thresh_low */
	{ 0x5228, 0x00000000, 26, 2 },	/* narr_txtr_thresh_high */
	{ 0x522c, 0x00000000, 28, 4 },	/* wmf_edge_limit_2 */
	{ 0x5230, 0x00000000, 32, 4 },	/* wmf_edge_limit_3 */
	{ 0x5234, 0x00000000, 36, 4 },	/* wmf_txtr_limit_2 */
	{ 0x5238, 0x00000000, 40, 4 },	/* wmf_txtr_limit_3 */
	{ 0x524c, 0x00000000, 44, 4 },	/* edge_limit */
	{ 0x5250, 0x00000000, 48, 4 },	/* txtr_limit */
	{ 0x5258, 0x00000000, 52, 2 },	/* radial_sharp */
	{ 0x525c, 0x00000000, 54, 1 },	/* radial_sharp_pow_min */
	{ 0x5260, 0x00000000, 55, 2 },	/* gf_sharp_thresh_low */
	{ 0x5264, 0x00000000, 57, 2 },	/* gf_sharp_thresh_high */
	{ 0x527c, 0x00000000, 59, 2 },	/* gf_sharp_power_total_gain_0_to_1 */
	{ 0x5280, 0x00000000, 61, 2 },	/* gf_sharp_power_total_gain_2_to_3 */
	{ 0x5284, 0x00000000, 63, 2 },	/* gf_sharp_power_total_gain_4_to_5 */
	{ 0x5288, 0x00000000, 65, 2 },	/* gf_sharp_power_total_gain_6_to_7 */
	{ 0x528c, 0x00000000, 67, 4 },	/* gf_sharp_limit */
	{ 0x52b4, 0x00000000, 71, 2 },	/* medi_edge_power_total_gain_0_to_1 */
	{ 0x52b8, 0x00000000, 73, 2 },	/* medi_edge_power_total_gain_2_to_3 */
	{ 0x52bc, 0x00000000, 75, 2 },	/* medi_edge_power_total_gain_4_to_5 */
	{ 0x52c0, 0x00000000, 77, 2 },	/* medi_edge_power_total_gain_6_to_7 */
	{ 0x52c4, 0x00000000, 79, 2 },	/* narr_edge_power_total_gain_0_to_1 */
	{ 0x52c8, 0x00000000, 81, 2 },	/* narr_edge_power_total_gain_2_to_3 */
	{ 0x52cc, 0x00000000, 83, 2 },	/* narr_edge_power_total_gain_4_to_5 */
	{ 0x52d0, 0x00000000, 85, 2 },	/* narr_edge_power_total_gain_6_to_7 */
	{ 0x52e4, 0x00000000, 87, 2 },	/* medi_txtr_power_total_gain_0_to_1 */
	{ 0x52e8, 0x00000000, 89, 2 },	/* medi_txtr_power_total_gain_2_to_3 */
	{ 0x52ec, 0x00000000, 91, 2 },	/* medi_txtr_power_total_gain_4_to_5 */
	{ 0x52f0, 0x00000000, 93, 2 },	/* medi_txtr_power_total_gain_6_to_7 */
	{ 0x52f4, 0x00000000, 95, 2 },	/* narr_txtr_power_total_gain_0_to_1 */
	{ 0x52f8, 0x00000000, 97, 2 },	/* narr_txtr_power_total_gain_2_to_3 */
	{ 0x52fc, 0x00000000, 99, 2 },	/* narr_txtr_power_total_gain_4_to_5 */
	{ 0x5300, 0x00000000, 101, 2 },	/* narr_txtr_power_total_gain_6_to_7 */
	{ 0x5318, 0x00000000, 103, 4 },	/* sharp_gain */
	{ 0x531c, 0x00000000, 107, 2 },	/* sharp_gain_1 */
	{ 0x5320, 0x02000000, 109, 1 },	/* invs_halo_grade */
	{ 0x5324, 0x00000000, 110, 2 },	/* invs_halo_texture_weight_offset */
	{ 0x5334, 0x00000000, 112, 4 },	/* wsharp_power */
	{ 0x5600, 0x00000000, 116, 3 },	/* config2 */
	{ 0x5604, 0x00000000, 119, 3 },	/* noise_gen_gain */
	{ 0x5608, 0x00000000, 122, 3 },	/* noise_gen_gain_shift */
	{ 0x5700, 0x00000000, 125, 3 },	/* noise_gain */
	{ 0x5704, 0x00000000, 128, 3 },	/* noise_gain_1 */
	{ 0x5708, 0x00000000, 131, 3 },	/* noise_gain_2 */
	{ 0x570c, 0x00000000, 134, 3 },	/* noise_gain_3 */
	{ 0x5720, 0x00000000, 137, 2 },	/* noise_gain_lut_total_gain */
	{ 0x5724, 0x00000000, 139, 2 },	/* noise_gain_lut_total_gain_1 */
	{ 0x5728, 0x00000000, 141, 2 },	/* noise_gain_lut_total_gain_2 */
	{ 0x572c, 0x00000000, 143, 2 },	/* noise_gain_lut_total_gain_3 */
	{ 0x5730, 0x00000000, 145, 4 },	/* config_en */
	{ 0x5734, 0x00000000, 149, 2 },	/* radial_noise */
	{ 0x5738, 0x00000000, 151, 1 },	/* radial_noise_pow_min */
	{ 0x5800, 0x00000000, 152, 21 },	/* control_config */
	{ 0x5824, 0x00000000, 173, 2 },	/* hue_range_0 */
	{ 0x5828, 0x00000000, 175, 2 },	/* sat_range_0 */
	{ 0x582c, 0x00000000, 177, 2 },	/* val_range_0 */
	{ 0x5834, 0x00000000, 179, 2 },	/* hue_range_1 */
	{ 0x5838, 0x00000000, 181, 2 },	/* sat_range_1 */
	{ 0x583c, 0x00000000, 183, 2 },	/* val_range_1 */
	{ 0x5844, 0x00000000, 185, 2 },	/* hue_range_2 */
	{ 0x5848, 0x00000000, 187, 2 },	/* sat_range_2 */
	{ 0x584c, 0x00000000, 189, 2 },	/* val_range_2 */
	{ 0x5854, 0x00000000, 191, 2 },	/* hue_range_3 */
	{ 0x5858, 0x00000000, 193, 2 },	/* sat_range_3 */
	{ 0x585c, 0x00000000, 195, 2 },	/* val_range_3 */
	{ 0x5864, 0x00000000, 197, 2 },	/* hue_range_4 */
	{ 0x5868, 0x00000000, 199, 2 },	/* sat_range_4 */
	{ 0x586c, 0x00000000, 201, 2 },	/* val_range_4 */
	{ 0x5888, 0x00000000, 203, 7 },	/* desat_1 */
	{ 0x588c, 0x00000000, 210, 2 },	/* desat_2 */
	{ 0x5890, 0x00000000, 212, 4 },	/* desat_3 */
	{ 0x5894, 0x00000000, 216, 2 },	/* desat_4 */
	{ 0x5898, 0x00000000, 218, 2 },	/* desat_5 */
	{ 0x589c, 0x00000000, 220, 2 },	/* desat_6 */
	{ 0x58a0, 0x00000000, 222, 2 },	/* desat_7 */
	{ 0x58a4, 0x00000000, 224, 2 },	/* desat_8 */
	{ 0x58a8, 0x00000000, 226, 2 },	/* desat_9 */
	{ 0x58ac, 0x00000000, 228, 2 },	/* desat_10 */
	{ 0x58b0, 0x00000000, 230, 6 },	/* desat_11 */
	{ 0x5900, 0x00000000, 236, 1 },	/* rgb_sharp_adder_config */
	{ 0x590c, 0x00000000, 237, 1 },	/* noise_power */
	{ 0x5910, 0x00000000, 238, 5 },	/* content_dependent_config1 */
	{ 0x5914, 0x00000000, 243, 2 },	/* content_dependent_config2 */
	{ 0x5918, 0x05000500, 245, 2 },	/* content_for_skin */
	{ 0x591c, 0x00000000, 247, 3 },	/* action_on_skin */
	{ 0x5920, 0x00000000, 250, 2 },	/* action_on_skin_1 */
	{ 0x5924, 0x00000000, 252, 6 },	/* content_dependent_cont_config1 */
	{ 0x5928, 0x00000000, 258, 7 },	/* content_dependent_cont_config2 */
	{ 0x592c, 0x00000000, 265, 7 },	/* content_dependent_cont_config3 */
	{ 0x5934, 0x00000000, 272, 1 },	/* skin_b_reduce_noise */
	{ 0x5938, 0x06000500, 273, 2 },	/* content_for_sky */
	{ 0x593c, 0x00000000, 275, 2 },	/* action_on_sky */
	{ 0x5940, 0x05000500, 277, 2 },	/* content_for_grass */
	{ 0x5944, 0x00000000, 279, 2 },	/* action_on_grass */
	{ 0x5948, 0x06002600, 281, 2 },	/* content_for_extra */
	{ 0x594c, 0x00000000, 283, 2 },	/* action_on_extra */
	{ 0x5954, 0x00000000, 285, 1 },	/* skin_face_brightness_gain */
	{ 0x59cc, 0x00000000, 286, 4 },	/* face_sharp_level */
	{ 0x59d0, 0x00000000, 290, 4 },	/* face_sharp_level_1 */
	{ 0x59d4, 0x00000000, 294, 2 },	/* face_sharp_level_2 */
	{ 0x59d8, 0x00000000, 296, 4 },	/* face_noise_level */
	{ 0x59dc, 0x00000000, 300, 4 },	/* face_noise_level_1 */
	{ 0x59e0, 0x00000000, 304, 2 },	/* face_noise_level_2 */
	{ 0x59e4, 0x00000000, 306, 4 },	/* face_brightness_level */
	{ 0x59e8, 0x00000000, 310, 4 },	/* face_brightness_level_1 */
	{ 0x59ec, 0x00000000, 314, 2 },	/* face_brightness_level_2 */
	{ 0x5a48, 0x00000000, 316, 1 },	/* invs_x_i_0 */
	{ 0x5a4c, 0x00000000, 317, 1 },	/* invs_x_i_1 */
	{ 0x5a50, 0x00000000, 318, 1 },	/* invs_x_i_2 */
	{ 0x5a54, 0x00000000, 319, 1 },	/* invs_x_i_3 */
	{ 0x5a58, 0x00000000, 320, 1 },	/* invs_x_i_4 */
	{ 0x5a5c, 0x00000000, 321, 1 },	/* invs_x_i_5 */
	{ 0x5a60, 0x00000000, 322, 1 },	/* invs_x_i_6 */
	{ 0x5a64, 0x00000000, 323, 1 },	/* invs_x_i_7 */
	{ 0x5a68, 0x00000000, 324, 1 },	/* invs_x_i_8 */
	{ 0x5a6c, 0x00000000, 325, 1 },	/* invs_x_i_9 */
	{ 0x5a70, 0x00000000, 326, 1 },	/* invs_y_i_0 */
	{ 0x5a74, 0x00000000, 327, 1 },	/* invs_y_i_1 */
	{ 0x5a78, 0x00000000, 328, 1 },	/* invs_y_i_2 */
	{ 0x5a7c, 0x00000000, 329, 1 },	/* invs_y_i_3 */
	{ 0x5a80, 0x00000000, 330, 1 },	/* invs_y_i_4 */
	{ 0x5a84, 0x00000000, 331, 1 },	/* invs_y_i_5 */
	{ 0x5a88, 0x00000000, 332, 1 },	/* invs_y_i_6 */
	{ 0x5a8c, 0x00000000, 333, 1 },	/* invs_y_i_7 */
	{ 0x5a90, 0x00000000, 334, 1 },	/* invs_y_i_8 */
	{ 0x5a94, 0x00000000, 335, 1 },	/* invs_y_i_9 */
	{ 0x5a98, 0x00000000, 336, 2 },	/* desat_config */
	{ 0x5a9c, 0x00000000, 338, 2 },	/* apply_desat_0 */
	{ 0x5aa0, 0x00000000, 340, 2 },	/* apply_desat_1 */
	{ 0x5aa4, 0x00000000, 342, 2 },	/* apply_desat_2 */
};

static_assert(ARRAY_SIZE(becore_sharpen_regs) == BECORE_SHARPEN_REGS);

/*
 * The same registers as ranges, for the generated table in the driver and for
 * the recipe generator that has to agree with it.
 */
#define BECORE_SHARPEN_RANGE(first, last)	\
	{ BECORE_YUVP_PHYS_BASE + (first),	\
	  BECORE_YUVP_PHYS_BASE + (last), BECORE_GEN_SHARPEN }

#define BECORE_SHARPEN_TUNING_RANGES \
	BECORE_SHARPEN_RANGE(0x5004, 0x5004), \
	BECORE_SHARPEN_RANGE(0x515c, 0x515c), \
	BECORE_SHARPEN_RANGE(0x5174, 0x5178), \
	BECORE_SHARPEN_RANGE(0x5188, 0x5188), \
	BECORE_SHARPEN_RANGE(0x5190, 0x5194), \
	BECORE_SHARPEN_RANGE(0x519c, 0x519c), \
	BECORE_SHARPEN_RANGE(0x5208, 0x5238), \
	BECORE_SHARPEN_RANGE(0x524c, 0x5250), \
	BECORE_SHARPEN_RANGE(0x5258, 0x5264), \
	BECORE_SHARPEN_RANGE(0x527c, 0x528c), \
	BECORE_SHARPEN_RANGE(0x52b4, 0x52d0), \
	BECORE_SHARPEN_RANGE(0x52e4, 0x5300), \
	BECORE_SHARPEN_RANGE(0x5318, 0x5324), \
	BECORE_SHARPEN_RANGE(0x5334, 0x5334), \
	BECORE_SHARPEN_RANGE(0x5600, 0x5608), \
	BECORE_SHARPEN_RANGE(0x5700, 0x570c), \
	BECORE_SHARPEN_RANGE(0x5720, 0x5738), \
	BECORE_SHARPEN_RANGE(0x5800, 0x5800), \
	BECORE_SHARPEN_RANGE(0x5824, 0x582c), \
	BECORE_SHARPEN_RANGE(0x5834, 0x583c), \
	BECORE_SHARPEN_RANGE(0x5844, 0x584c), \
	BECORE_SHARPEN_RANGE(0x5854, 0x585c), \
	BECORE_SHARPEN_RANGE(0x5864, 0x586c), \
	BECORE_SHARPEN_RANGE(0x5888, 0x58b0), \
	BECORE_SHARPEN_RANGE(0x5900, 0x5900), \
	BECORE_SHARPEN_RANGE(0x590c, 0x592c), \
	BECORE_SHARPEN_RANGE(0x5934, 0x594c), \
	BECORE_SHARPEN_RANGE(0x5954, 0x5954), \
	BECORE_SHARPEN_RANGE(0x59cc, 0x59ec), \
	BECORE_SHARPEN_RANGE(0x5a48, 0x5aa4),

#endif /* __EXYNOS_BECORE_SHARPEN_H */
