/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by tools/camera-becore-recipe.py; do not edit. */
/* GTNR startup snapshot 5:
 * shape   d19af27ddce4252e926870f9474415d26e19c363b966870f8c1243cf1b510ba9
 * payload 07acce169d372e054ffe2b86d34cad04adf628013010a9c73a9da1895bc10ba5
 */
#ifndef __EXYNOS_BECORE_GTNR_RECIPE_H__
#define __EXYNOS_BECORE_GTNR_RECIPE_H__

#include "exynos-becore-recipe.h"

#define BECORE_GTNR_RECIPE_MAGIC 0x31525447
#define BECORE_GTNR_RECIPE_VERSION 1
#define BECORE_GTNR_RECIPE_HEADER_BYTES 32
#define BECORE_GTNR_RECIPE_RECORD_BYTES 76
#define BECORE_GTNR_HEADER_COUNT 13
#define BECORE_GTNR_RECIPE_BYTES \
	(BECORE_GTNR_RECIPE_HEADER_BYTES + \
	 BECORE_GTNR_RECIPE_RECORD_BYTES * BECORE_GTNR_HEADER_COUNT)

static const struct becore_cmdq_shape becore_gtnr_shape[] = {
	{ /* h000 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0xaaa0,
		.pair_registers = {
			0x1cc43288, 0x1cc43214, 0x1cc42200, 0x1cc42a00,
			0x1cc42400, 0x1cc42c00, 0x1cc42600, 0x1cc42e00,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h001 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43200, 0x1cc43218, 0x1cc4321c, 0x1cc43230,
			0x1cc43234, 0x1cc43238, 0x1cc4323c, 0x1cc43240,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h002 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x8000,
		.pair_registers = {
			0x1cc43244, 0x1cc43248, 0x1cc4324c, 0x1cc43254,
			0x1cc43250, 0x1cc43204, 0x1cc43208, 0x1cc42800,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h003 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0028,
		.typed_mask = 0xaa80,
		.fixed_mask = 0x0002,
		.pair_registers = {
			0x1cc42804, 0x1cc41e50, 0x1cc41e90, 0x1cc41e3c,
			0x1cc41e10, 0x1cc41e18, 0x1cc41e04, 0x1cc41e20,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h004 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.typed_mask = 0x2aaa,
		.fixed_mask = 0x8000,
		.pair_registers = {
			0x1cc41e24, 0x1cc41e28, 0x1cc41e2c, 0x1cc41e4c,
			0x1cc41e40, 0x1cc41e48, 0x1cc41e00, 0x1cc42000,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h005 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0aaa,
		.pair_registers = {
			0x1cc42004, 0x1cc41a00, 0x1cc41a04, 0x1cc41c00,
			0x1cc41c04, 0x1cc41800, 0x1cc43300, 0x1cc43308,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h006 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43304, 0x1cc43420, 0x1cc4341c, 0x1cc43310,
			0x1cc43314, 0x1cc43318, 0x1cc4331c, 0x1cc43320,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h007 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43354, 0x1cc43358, 0x1cc4335c, 0x1cc43378,
			0x1cc4337c, 0x1cc43380, 0x1cc4339c, 0x1cc433a0,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h008 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc433a4, 0x1cc433c0, 0x1cc433c4, 0x1cc433c8,
			0x1cc433cc, 0x1cc433d0, 0x1cc433d4, 0x1cc433d8,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h009 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc433dc, 0x1cc433e0, 0x1cc433e4, 0x1cc433e8,
			0x1cc433ec, 0x1cc433f0, 0x1cc433f4, 0x1cc433f8,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h010 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0a00,
		.typed_mask = 0xa000,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43400, 0x1cc43404, 0x1cc43408, 0x1cc4340c,
			0x1cc43050, 0x1cc43090, 0x1cc43010, 0x1cc43018,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h011 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x55555555,
		.valid_words = 16,
		.address_mask = 0x0000,
		.typed_mask = 0xaaaa,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43004, 0x1cc43020, 0x1cc43024, 0x1cc43028,
			0x1cc4302c, 0x1cc4304c, 0x1cc43040, 0x1cc43048,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
	{ /* h012 */
		.mode = 0x00090000,
		.target = 0x00000000,
		.type_map = 0x00000005,
		.valid_words = 2,
		.address_mask = 0x0000,
		.typed_mask = 0x0002,
		.fixed_mask = 0x0000,
		.pair_registers = {
			0x1cc43000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
		.fixed_values = {
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
			0x00000000, 0x00000000, 0x00000000, 0x00000000,
		},
	},
};

#endif /* __EXYNOS_BECORE_GTNR_RECIPE_H__ */
