# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_EXYNOS_BECORE) += exynos-becore.o

exynos-becore-y := exynos-becore-core.o exynos-becore-generated.o \
		   exynos-becore-geometry.o exynos-becore-params.o \
		   exynos-becore-recipe.o exynos-becore-video.o
