/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Device Tree binding constants for Google Zumapro clock controllers.
 */

#ifndef _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_H
#define _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_H

/* CMU_TOP fixed PLL-derived parents */
#define CLK_FOUT_SHARED0_D4			1
#define CLK_FOUT_SHARED2_D2			2
#define CLK_FOUT_SHARED3_D2			3
#define CLK_FOUT_SPARE_PLL			4
#define CLK_FOUT_SHARED1_D4			17
#define CLK_FOUT_SHARED2_D1			18
#define CLK_FOUT_SHARED3_D1			19

/* CMU_TOP muxes */
#define CLK_MOUT_CMU_PERIC0_NOC		5
#define CLK_MOUT_CMU_PERIC0_IP			6
#define CLK_MOUT_CMU_PERIC1_NOC		11
#define CLK_MOUT_CMU_PERIC1_IP			12
#define CLK_MOUT_CMU_HSI2_MMC_CARD		20
#define CLK_MOUT_CMU_HSI2_NOC			21
#define CLK_MOUT_CMU_HSI2_PCIE			22
#define CLK_MOUT_CMU_HSI2_UFS_EMBD		23

/* CMU_TOP gates */
#define CLK_GOUT_CMU_PERIC0_NOC		7
#define CLK_GOUT_CMU_PERIC0_IP			8
#define CLK_GOUT_CMU_PERIC1_NOC		13
#define CLK_GOUT_CMU_PERIC1_IP			14
#define CLK_GOUT_CMU_HSI2_MMC_CARD		24
#define CLK_GOUT_CMU_HSI2_NOC			25
#define CLK_GOUT_CMU_HSI2_PCIE			26
#define CLK_GOUT_CMU_HSI2_UFS_EMBD		27

/* CMU_TOP dividers */
#define CLK_DOUT_CMU_PERIC0_NOC		9
#define CLK_DOUT_CMU_PERIC0_IP			10
#define CLK_DOUT_CMU_PERIC1_NOC		15
#define CLK_DOUT_CMU_PERIC1_IP			16
#define CLK_DOUT_CMU_HSI2_MMC_CARD		28
#define CLK_DOUT_CMU_HSI2_NOC			29
#define CLK_DOUT_CMU_HSI2_PCIE			30
#define CLK_DOUT_CMU_HSI2_UFS_EMBD		31

/* CMU_PERIC0 muxes */
#define CLK_MOUT_PERIC0_NOC_USER		1
#define CLK_MOUT_PERIC0_USI0_UART_USER		2

/* CMU_PERIC0 dividers */
#define CLK_DOUT_PERIC0_USI0_UART		3

/* CMU_PERIC0 gates */
#define CLK_GOUT_PERIC0_GPIO_PERIC0_PCLK	4
#define CLK_GOUT_PERIC0_SYSREG_PERIC0_PCLK	5
#define CLK_GOUT_PERIC0_CMU_PERIC0_PCLK		6
#define CLK_GOUT_PERIC0_USI0_UART_IPCLK		7
#define CLK_GOUT_PERIC0_USI0_UART_PCLK		8
#define CLK_GOUT_PERIC0_USI0_UART_CLK		9

/* CMU_PERIC0 USI6 clocks */
#define CLK_MOUT_PERIC0_USI6_USI_USER		10
#define CLK_DOUT_PERIC0_USI6_USI		11
#define CLK_GOUT_PERIC0_USI6_USI_PCLK		12
#define CLK_GOUT_PERIC0_USI6_USI_CLK		13

/* CMU_PERIC1 muxes */
#define CLK_MOUT_PERIC1_NOC_USER		1
#define CLK_MOUT_PERIC1_USI10_USI_USER		2

/* CMU_PERIC1 dividers */
#define CLK_DOUT_PERIC1_USI10_USI		3

/* CMU_PERIC1 gates */
#define CLK_GOUT_PERIC1_GPIO_PERIC1_PCLK	4
#define CLK_GOUT_PERIC1_SYSREG_PERIC1_PCLK	5
#define CLK_GOUT_PERIC1_CMU_PERIC1_PCLK		6
#define CLK_GOUT_PERIC1_USI10_USI_PCLK		7
#define CLK_GOUT_PERIC1_USI10_USI_IPCLK		8
#define CLK_GOUT_PERIC1_USI10_USI_CLK		9

/* CMU_HSI2 muxes */
#define CLK_MOUT_HSI2_MMC_CARD_USER		1
#define CLK_MOUT_HSI2_NOC_USER			2
#define CLK_MOUT_HSI2_PCIE_USER			3
#define CLK_MOUT_HSI2_UFS_EMBD_USER		4

/* CMU_HSI2 gates */
#define CLK_GOUT_HSI2_GPIO_HSI2UFS_PCLK		5
#define CLK_GOUT_HSI2_CMU_HSI2_PCLK		6
#define CLK_GOUT_HSI2_SYSREG_HSI2_PCLK		7
#define CLK_GOUT_HSI2_UFS_EMBD_I_ACLK		8
#define CLK_GOUT_HSI2_UFS_EMBD_I_CLK_UNIPRO	9
#define CLK_GOUT_HSI2_UFS_EMBD_I_FMP_CLK	10
#define CLK_GOUT_HSI2_QE_UFS_EMBD_HSI2_ACLK	11
#define CLK_GOUT_HSI2_QE_UFS_EMBD_HSI2_PCLK	12

#endif /* _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_H */
