/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Device Tree binding constants for Google Zumapro ACPM clock controller.
 */

#ifndef _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_ACPM_H
#define _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_ACPM_H

#define ZUMAPRO_CLK_ACPM_DVFS_MIF			0
#define ZUMAPRO_CLK_ACPM_DVFS_INT			1
#define ZUMAPRO_CLK_ACPM_DVFS_CPUCL0			2
#define ZUMAPRO_CLK_ACPM_DVFS_CPUCL1			3
#define ZUMAPRO_CLK_ACPM_DVFS_CPUCL2			4
#define ZUMAPRO_CLK_ACPM_DVFS_DSU			5
#define ZUMAPRO_CLK_ACPM_DVFS_BCI			6
#define ZUMAPRO_CLK_ACPM_DVFS_G3D			7
#define ZUMAPRO_CLK_ACPM_DVFS_G3DL2			8
#define ZUMAPRO_CLK_ACPM_DVFS_TPU			9
#define ZUMAPRO_CLK_ACPM_DVFS_INTCAM			10
#define ZUMAPRO_CLK_ACPM_DVFS_TNR			11
#define ZUMAPRO_CLK_ACPM_DVFS_CAM			12
#define ZUMAPRO_CLK_ACPM_DVFS_MFC			13

#endif /* _DT_BINDINGS_CLOCK_GOOGLE_ZUMAPRO_ACPM_H */
