/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Interconnect IDs for Google Zumapro.
 */

#ifndef __DT_BINDINGS_INTERCONNECT_GOOGLE_ZUMAPRO_H
#define __DT_BINDINGS_INTERCONNECT_GOOGLE_ZUMAPRO_H

#define ZUMAPRO_BTS_MASTER_ISPFE		0
#define ZUMAPRO_BTS_SLAVE_MIF			1

#endif /* __DT_BINDINGS_INTERCONNECT_GOOGLE_ZUMAPRO_H */
